packages:
  - apps/*
  - packages/*

engineStrict: true
saveExact: true
strictPeerDependencies: true

allowBuilds:
  unrs-resolver: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - next@16.3.3
