packages:
  - apps/*
  - packages/*

engineStrict: true
saveExact: true
strictPeerDependencies: true
fetchRetries: 5
fetchRetryFactor: 2
fetchRetryMintimeout: 10000
fetchRetryMaxtimeout: 120000
fetchTimeout: 600000

allowBuilds:
  unrs-resolver: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - next@16.3.3
