/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API service information */
        get: operations["getServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check process liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check database and migration readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guest-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a device-scoped guest session */
        post: operations["createGuestSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guest-sessions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a device credential and issue fresh access */
        post: operations["refreshGuestSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guest-sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke the authenticated guest session */
        delete: operations["revokeGuestSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a private waiting table */
        post: operations["createTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tables/{inviteCode}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        /** Preview a private invite without joining */
        get: operations["previewTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tables/{inviteCode}/join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join an available private table */
        post: operations["joinTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tables/{tableId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        /** Get recipient-projected table state */
        get: operations["getTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tables/{tableId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave a waiting table and release its seat */
        post: operations["leaveTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/realtime/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a single-use WebSocket ticket */
        post: operations["createRealtimeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "ready" | "unavailable";
            service: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            requestId?: string;
            code?: string;
            messageKey?: string;
            retryable?: boolean;
        };
        CreateGuestSessionRequest: {
            nickname: string;
        };
        RefreshGuestSessionRequest: {
            deviceCredential: string;
        };
        GuestCredentials: {
            /** Format: uuid */
            sessionId: string;
            nickname: string;
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            deviceCredential: string;
        };
        RealtimeTicket: {
            ticket: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @enum {string} */
        TableState: "WAITING" | "ACTIVE" | "BETWEEN_BOARDS" | "FINISHED" | "PAUSED";
        /** @enum {string} */
        TableRole: "OWNER" | "PARTICIPANT";
        /** @enum {string} */
        TableSeat: "N" | "E" | "S" | "W";
        TableParticipant: {
            /** Format: uuid */
            id: string;
            nickname: string;
            role: components["schemas"]["TableRole"];
            isBot: boolean;
        };
        TableSeatAssignment: {
            /** Format: uuid */
            participantId: string;
            ready: boolean;
            /** Format: int64 */
            controllerEpoch: number;
            isBot?: boolean;
        };
        TableView: {
            /** Format: uuid */
            tableId: string;
            state: components["schemas"]["TableState"];
            locked: boolean;
            /** Format: int64 */
            revision: number;
            /** Format: int64 */
            lastSeq: number;
            /** Format: uuid */
            boardId?: string;
            boardNumber: number;
            /** Format: uuid */
            viewerParticipantId: string;
            viewerRole: components["schemas"]["TableRole"];
            viewerSeat?: components["schemas"]["TableSeat"];
            participants: components["schemas"]["TableParticipant"][];
            seats: {
                [key: string]: components["schemas"]["TableSeatAssignment"];
            };
        };
        CreateTableResponse: {
            inviteCode: string;
            table: components["schemas"]["TableView"];
        };
        TablePreview: {
            state: components["schemas"]["TableState"];
            locked: boolean;
            participantCount: number;
            capacity: number;
        };
    };
    responses: {
        /** @description The request was rejected */
        ProblemResponse: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        InviteCode: string;
        TableId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation identifier for the request. */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is serving requests */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "service": "bridgeyok-api"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "service": "api"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API dependencies are ready */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready",
                     *       "service": "api"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A required dependency is unavailable */
            503: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unavailable",
                     *       "service": "api"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    createGuestSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuestSessionRequest"];
            };
        };
        responses: {
            /** @description Guest session created */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestCredentials"];
                };
            };
            400: components["responses"]["ProblemResponse"];
        };
    };
    refreshGuestSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshGuestSessionRequest"];
            };
        };
        responses: {
            /** @description Guest credentials rotated */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestCredentials"];
                };
            };
            401: components["responses"]["ProblemResponse"];
        };
    };
    revokeGuestSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guest session revoked */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemResponse"];
        };
    };
    createTable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table created */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTableResponse"];
                };
            };
            401: components["responses"]["ProblemResponse"];
        };
    };
    previewTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Non-identifying table preview */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePreview"];
                };
            };
            404: components["responses"]["ProblemResponse"];
        };
    };
    joinTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant joined or existing participation resumed */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableView"];
                };
            };
            401: components["responses"]["ProblemResponse"];
            404: components["responses"]["ProblemResponse"];
            409: components["responses"]["ProblemResponse"];
        };
    };
    getTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized table state */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableView"];
                };
            };
            401: components["responses"]["ProblemResponse"];
            404: components["responses"]["ProblemResponse"];
        };
    };
    leaveTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant left the table */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemResponse"];
            404: components["responses"]["ProblemResponse"];
            409: components["responses"]["ProblemResponse"];
        };
    };
    createRealtimeTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Realtime ticket issued */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeTicket"];
                };
            };
            401: components["responses"]["ProblemResponse"];
        };
    };
}
