/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BridgeYokRealtimeEnvelope =
  CommandEnvelope | AckEnvelope | EventEnvelope | ErrorEnvelope | SnapshotEnvelope | ControlEnvelope;
export type CommandEnvelope = SubscriptionCommandEnvelope | MutationCommandEnvelope | ChatCommandEnvelope;
export type Version = 1;
export type RequestId = string;
export type TableId = string;
export type Sequence = number;
export type MutationCommandEnvelope = {
  v: Version;
  kind: "command";
  name:
    | "table.take_seat"
    | "table.leave_seat"
    | "table.set_ready"
    | "table.lock"
    | "table.remove_participant"
    | "table.add_bot"
    | "table.remove_bot"
    | "table.replace_with_bot"
    | "table.start_game"
    | "game.make_call"
    | "game.play_card"
    | "game.request_claim"
    | "game.respond_claim"
    | "game.request_undo"
    | "game.respond_undo"
    | "table.next_board"
    | "table.finish"
    | "table.leave"
    | "table.takeover";
  request_id: RequestId;
  table_id: TableId;
  expected_revision: Revision;
  controller_epoch?: number;
  payload: Payload;
};
export type Revision = number;
export type ChatCommandEnvelope = {
  v: Version;
  kind: "command";
  name: "chat.private.send" | "chat.table.send";
  request_id: RequestId;
  payload: {
    target: {
      scope: "private" | "table";
      id: string;
    };
    /**
     * At most 1000 Unicode grapheme clusters and 16000 UTF-8 bytes; reject blank or NUL. Never truncate.
     */
    content: string;
  };
};
export type MessageName = string;
export type ControlEnvelope = {
  v: Version;
  kind: "control";
  name: MessageName;
  request_id?: RequestId;
  table_id?: TableId;
  payload: Payload;
};

export interface SubscriptionCommandEnvelope {
  v: Version;
  kind: "command";
  name: "table.subscribe" | "table.resume";
  request_id: RequestId;
  table_id: TableId;
  payload: SubscriptionPayload;
}
export interface SubscriptionPayload {
  last_seen_seq: Sequence;
}
export interface Payload {
  [k: string]: unknown;
}
export interface AckEnvelope {
  v: Version;
  kind: "ack";
  name: MessageName;
  request_id: RequestId;
  table_id: TableId;
  revision: Revision;
  seq: Sequence;
  payload: AckPayload;
}
export interface AckPayload {
  status: "accepted";
  duplicate: boolean;
  syncMode?: "events" | "snapshot";
}
export interface EventEnvelope {
  v: Version;
  kind: "event";
  name: MessageName;
  table_id: TableId;
  revision: Revision;
  seq: Sequence;
  payload: ProjectedEventPayload;
}
export interface ProjectedEventPayload {
  eventType: string;
  table: TableProjection;
}
export interface TableProjection {
  tableId: TableId;
  state: "WAITING" | "ACTIVE" | "BETWEEN_BOARDS" | "FINISHED";
  locked: boolean;
  revision: Revision;
  lastSeq: Sequence;
  boardId?: TableId;
  boardNumber: number;
  scoreSheet: ScoreSheetEntry[];
  pairScoreTotals: PairScoreTotal[];
  viewerParticipantId: string;
  viewerRole: "OWNER" | "PARTICIPANT";
  viewerSeat?: "N" | "E" | "S" | "W";
  participants: ProjectedParticipant[];
  seats: {
    N?: SeatAssignment;
    E?: SeatAssignment;
    S?: SeatAssignment;
    W?: SeatAssignment;
  };
  game?: {
    [k: string]: unknown;
  };
  actionRequest?: ActionRequest;
  canRequestUndo: boolean;
}
export interface ScoreSheetEntry {
  boardId: TableId;
  boardNumber: number;
  result: ScoreSheetResult;
  lineup: BoardLineup;
}
export interface ScoreSheetResult {
  rulesetVersion: string;
  passedOut: boolean;
  contract?: ScoreContract;
  tricksDeclarer: number;
  tricksNS: number;
  tricksEW: number;
  vulnerability: "NONE" | "NS" | "EW" | "BOTH";
  scoreNS: number;
}
export interface ScoreContract {
  level: number;
  strain: "C" | "D" | "H" | "S" | "NT";
  doubling: "UNDOUBLED" | "DOUBLED" | "REDOUBLED";
  declarer: "N" | "E" | "S" | "W";
}
export interface BoardLineup {
  seats: {
    N: ScoreParticipant;
    E: ScoreParticipant;
    S: ScoreParticipant;
    W: ScoreParticipant;
  };
  northSouth: ScorePair;
  eastWest: ScorePair;
}
export interface ScoreParticipant {
  id: string;
  nickname: string;
  isBot: boolean;
}
export interface ScorePair {
  id: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  members: [ScoreParticipant, ScoreParticipant];
}
export interface PairScoreTotal {
  pair: ScorePair;
  score: number;
}
export interface ProjectedParticipant {
  id: string;
  nickname: string;
  role: "OWNER" | "PARTICIPANT";
  isBot: boolean;
}
export interface SeatAssignment {
  participantId: string;
  ready: boolean;
  controllerEpoch: number;
  isBot?: boolean;
}
export interface ActionRequest {
  kind: "CLAIM" | "UNDO";
  requesterSeat: "N" | "E" | "S" | "W";
  claimTricks?: number;
  approvedBy: ("N" | "E" | "S" | "W")[];
  canRespond: boolean;
}
export interface ErrorEnvelope {
  v: Version;
  kind: "error";
  name: MessageName;
  request_id?: RequestId;
  table_id?: TableId;
  code: string;
  retryable: boolean;
  revision?: Revision;
  seq?: Sequence;
  payload: EmptyPayload;
}
export interface EmptyPayload {}
export interface SnapshotEnvelope {
  v: Version;
  kind: "snapshot";
  name: MessageName;
  table_id: TableId;
  revision: Revision;
  seq: Sequence;
  payload: TableProjection;
}
