/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BridgeYokRealtimeEnvelope =
  CommandEnvelope | AckEnvelope | EventEnvelope | ErrorEnvelope | SnapshotEnvelope | ControlEnvelope;
export type Version = 1;
export type MessageName = string;
export type RequestId = string;
export type TableId = string;
export type Revision = number;
export type Sequence = number;

export interface CommandEnvelope {
  v: Version;
  kind: "command";
  name: MessageName;
  request_id: RequestId;
  table_id: TableId;
  expected_revision?: Revision;
  payload: Payload;
}
export interface Payload {
  [k: string]: unknown;
}
export interface AckEnvelope {
  v: Version;
  kind: "ack";
  name: MessageName;
  request_id: RequestId;
  table_id: TableId;
  revision: Revision;
  seq: Sequence;
  payload: Payload;
}
export interface EventEnvelope {
  v: Version;
  kind: "event";
  name: MessageName;
  table_id: TableId;
  revision: Revision;
  seq: Sequence;
  payload: Payload;
}
export interface ErrorEnvelope {
  v: Version;
  kind: "error";
  name: MessageName;
  request_id?: RequestId;
  table_id?: TableId;
  code: string;
  retryable: boolean;
  payload: Payload;
}
export interface SnapshotEnvelope {
  v: Version;
  kind: "snapshot";
  name: MessageName;
  table_id: TableId;
  revision: Revision;
  seq: Sequence;
  payload: Payload;
}
export interface ControlEnvelope {
  v: Version;
  kind: "control";
  name: MessageName;
  request_id?: RequestId;
  table_id?: TableId;
  payload: Payload;
}
