// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AnalysisResultSolverVersion.
const (
	Dds2908d75755 AnalysisResultSolverVersion = "dds-2.9.0-8d75755"
)

// Valid indicates whether the value is a known member of the AnalysisResultSolverVersion enum.
func (e AnalysisResultSolverVersion) Valid() bool {
	switch e {
	case Dds2908d75755:
		return true
	default:
		return false
	}
}

// Defines values for AnalysisStrain.
const (
	AnalysisStrainC  AnalysisStrain = "C"
	AnalysisStrainD  AnalysisStrain = "D"
	AnalysisStrainH  AnalysisStrain = "H"
	AnalysisStrainNT AnalysisStrain = "NT"
	AnalysisStrainS  AnalysisStrain = "S"
)

// Valid indicates whether the value is a known member of the AnalysisStrain enum.
func (e AnalysisStrain) Valid() bool {
	switch e {
	case AnalysisStrainC:
		return true
	case AnalysisStrainD:
		return true
	case AnalysisStrainH:
		return true
	case AnalysisStrainNT:
		return true
	case AnalysisStrainS:
		return true
	default:
		return false
	}
}

// Defines values for BoardAnalysisMetadataVulnerability.
const (
	BoardAnalysisMetadataVulnerabilityBOTH BoardAnalysisMetadataVulnerability = "BOTH"
	BoardAnalysisMetadataVulnerabilityEW   BoardAnalysisMetadataVulnerability = "EW"
	BoardAnalysisMetadataVulnerabilityNONE BoardAnalysisMetadataVulnerability = "NONE"
	BoardAnalysisMetadataVulnerabilityNS   BoardAnalysisMetadataVulnerability = "NS"
)

// Valid indicates whether the value is a known member of the BoardAnalysisMetadataVulnerability enum.
func (e BoardAnalysisMetadataVulnerability) Valid() bool {
	switch e {
	case BoardAnalysisMetadataVulnerabilityBOTH:
		return true
	case BoardAnalysisMetadataVulnerabilityEW:
		return true
	case BoardAnalysisMetadataVulnerabilityNONE:
		return true
	case BoardAnalysisMetadataVulnerabilityNS:
		return true
	default:
		return false
	}
}

// Defines values for BoardAnalysisProvenanceType.
const (
	Constraint    BoardAnalysisProvenanceType = "constraint"
	Deterministic BoardAnalysisProvenanceType = "deterministic"
	Prepared      BoardAnalysisProvenanceType = "prepared"
	SecureRandom  BoardAnalysisProvenanceType = "secure_random"
)

// Valid indicates whether the value is a known member of the BoardAnalysisProvenanceType enum.
func (e BoardAnalysisProvenanceType) Valid() bool {
	switch e {
	case Constraint:
		return true
	case Deterministic:
		return true
	case Prepared:
		return true
	case SecureRandom:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Ready       HealthResponseStatus = "ready"
	Unavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Ready:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for ReplayCallKind.
const (
	BID      ReplayCallKind = "BID"
	DOUBLE   ReplayCallKind = "DOUBLE"
	PASS     ReplayCallKind = "PASS"
	REDOUBLE ReplayCallKind = "REDOUBLE"
)

// Valid indicates whether the value is a known member of the ReplayCallKind enum.
func (e ReplayCallKind) Valid() bool {
	switch e {
	case BID:
		return true
	case DOUBLE:
		return true
	case PASS:
		return true
	case REDOUBLE:
		return true
	default:
		return false
	}
}

// Defines values for ReplayCallStrain.
const (
	ReplayCallStrainC  ReplayCallStrain = "C"
	ReplayCallStrainD  ReplayCallStrain = "D"
	ReplayCallStrainH  ReplayCallStrain = "H"
	ReplayCallStrainNT ReplayCallStrain = "NT"
	ReplayCallStrainS  ReplayCallStrain = "S"
)

// Valid indicates whether the value is a known member of the ReplayCallStrain enum.
func (e ReplayCallStrain) Valid() bool {
	switch e {
	case ReplayCallStrainC:
		return true
	case ReplayCallStrainD:
		return true
	case ReplayCallStrainH:
		return true
	case ReplayCallStrainNT:
		return true
	case ReplayCallStrainS:
		return true
	default:
		return false
	}
}

// Defines values for ReplayCardRank.
const (
	A  ReplayCardRank = "A"
	J  ReplayCardRank = "J"
	K  ReplayCardRank = "K"
	N2 ReplayCardRank = "2"
	N3 ReplayCardRank = "3"
	N4 ReplayCardRank = "4"
	N5 ReplayCardRank = "5"
	N6 ReplayCardRank = "6"
	N7 ReplayCardRank = "7"
	N8 ReplayCardRank = "8"
	N9 ReplayCardRank = "9"
	Q  ReplayCardRank = "Q"
	T  ReplayCardRank = "T"
)

// Valid indicates whether the value is a known member of the ReplayCardRank enum.
func (e ReplayCardRank) Valid() bool {
	switch e {
	case A:
		return true
	case J:
		return true
	case K:
		return true
	case N2:
		return true
	case N3:
		return true
	case N4:
		return true
	case N5:
		return true
	case N6:
		return true
	case N7:
		return true
	case N8:
		return true
	case N9:
		return true
	case Q:
		return true
	case T:
		return true
	default:
		return false
	}
}

// Defines values for ReplayCardSuit.
const (
	ReplayCardSuitC ReplayCardSuit = "C"
	ReplayCardSuitD ReplayCardSuit = "D"
	ReplayCardSuitH ReplayCardSuit = "H"
	ReplayCardSuitS ReplayCardSuit = "S"
)

// Valid indicates whether the value is a known member of the ReplayCardSuit enum.
func (e ReplayCardSuit) Valid() bool {
	switch e {
	case ReplayCardSuitC:
		return true
	case ReplayCardSuitD:
		return true
	case ReplayCardSuitH:
		return true
	case ReplayCardSuitS:
		return true
	default:
		return false
	}
}

// Defines values for ReplayContractDeclarer.
const (
	ReplayContractDeclarerE ReplayContractDeclarer = "E"
	ReplayContractDeclarerN ReplayContractDeclarer = "N"
	ReplayContractDeclarerS ReplayContractDeclarer = "S"
	ReplayContractDeclarerW ReplayContractDeclarer = "W"
)

// Valid indicates whether the value is a known member of the ReplayContractDeclarer enum.
func (e ReplayContractDeclarer) Valid() bool {
	switch e {
	case ReplayContractDeclarerE:
		return true
	case ReplayContractDeclarerN:
		return true
	case ReplayContractDeclarerS:
		return true
	case ReplayContractDeclarerW:
		return true
	default:
		return false
	}
}

// Defines values for ReplayContractDoubling.
const (
	DOUBLED   ReplayContractDoubling = "DOUBLED"
	REDOUBLED ReplayContractDoubling = "REDOUBLED"
	UNDOUBLED ReplayContractDoubling = "UNDOUBLED"
)

// Valid indicates whether the value is a known member of the ReplayContractDoubling enum.
func (e ReplayContractDoubling) Valid() bool {
	switch e {
	case DOUBLED:
		return true
	case REDOUBLED:
		return true
	case UNDOUBLED:
		return true
	default:
		return false
	}
}

// Defines values for ReplayContractStrain.
const (
	ReplayContractStrainC  ReplayContractStrain = "C"
	ReplayContractStrainD  ReplayContractStrain = "D"
	ReplayContractStrainH  ReplayContractStrain = "H"
	ReplayContractStrainNT ReplayContractStrain = "NT"
	ReplayContractStrainS  ReplayContractStrain = "S"
)

// Valid indicates whether the value is a known member of the ReplayContractStrain enum.
func (e ReplayContractStrain) Valid() bool {
	switch e {
	case ReplayContractStrainC:
		return true
	case ReplayContractStrainD:
		return true
	case ReplayContractStrainH:
		return true
	case ReplayContractStrainNT:
		return true
	case ReplayContractStrainS:
		return true
	default:
		return false
	}
}

// Defines values for ReplayGameBoardVulnerability.
const (
	ReplayGameBoardVulnerabilityBOTH ReplayGameBoardVulnerability = "BOTH"
	ReplayGameBoardVulnerabilityEW   ReplayGameBoardVulnerability = "EW"
	ReplayGameBoardVulnerabilityNONE ReplayGameBoardVulnerability = "NONE"
	ReplayGameBoardVulnerabilityNS   ReplayGameBoardVulnerability = "NS"
)

// Valid indicates whether the value is a known member of the ReplayGameBoardVulnerability enum.
func (e ReplayGameBoardVulnerability) Valid() bool {
	switch e {
	case ReplayGameBoardVulnerabilityBOTH:
		return true
	case ReplayGameBoardVulnerabilityEW:
		return true
	case ReplayGameBoardVulnerabilityNONE:
		return true
	case ReplayGameBoardVulnerabilityNS:
		return true
	default:
		return false
	}
}

// Defines values for ReplayGamePhase.
const (
	BOARDSCORED ReplayGamePhase = "BOARD_SCORED"
)

// Valid indicates whether the value is a known member of the ReplayGamePhase enum.
func (e ReplayGamePhase) Valid() bool {
	switch e {
	case BOARDSCORED:
		return true
	default:
		return false
	}
}

// Defines values for ReplayResultVulnerability.
const (
	ReplayResultVulnerabilityBOTH ReplayResultVulnerability = "BOTH"
	ReplayResultVulnerabilityEW   ReplayResultVulnerability = "EW"
	ReplayResultVulnerabilityNONE ReplayResultVulnerability = "NONE"
	ReplayResultVulnerabilityNS   ReplayResultVulnerability = "NS"
)

// Valid indicates whether the value is a known member of the ReplayResultVulnerability enum.
func (e ReplayResultVulnerability) Valid() bool {
	switch e {
	case ReplayResultVulnerabilityBOTH:
		return true
	case ReplayResultVulnerabilityEW:
		return true
	case ReplayResultVulnerabilityNONE:
		return true
	case ReplayResultVulnerabilityNS:
		return true
	default:
		return false
	}
}

// Defines values for ReplayTrickLeader.
const (
	ReplayTrickLeaderE     ReplayTrickLeader = "E"
	ReplayTrickLeaderEmpty ReplayTrickLeader = ""
	ReplayTrickLeaderN     ReplayTrickLeader = "N"
	ReplayTrickLeaderS     ReplayTrickLeader = "S"
	ReplayTrickLeaderW     ReplayTrickLeader = "W"
)

// Valid indicates whether the value is a known member of the ReplayTrickLeader enum.
func (e ReplayTrickLeader) Valid() bool {
	switch e {
	case ReplayTrickLeaderE:
		return true
	case ReplayTrickLeaderEmpty:
		return true
	case ReplayTrickLeaderN:
		return true
	case ReplayTrickLeaderS:
		return true
	case ReplayTrickLeaderW:
		return true
	default:
		return false
	}
}

// Defines values for TableRole.
const (
	OWNER       TableRole = "OWNER"
	PARTICIPANT TableRole = "PARTICIPANT"
)

// Valid indicates whether the value is a known member of the TableRole enum.
func (e TableRole) Valid() bool {
	switch e {
	case OWNER:
		return true
	case PARTICIPANT:
		return true
	default:
		return false
	}
}

// Defines values for TableSeat.
const (
	TableSeatE TableSeat = "E"
	TableSeatN TableSeat = "N"
	TableSeatS TableSeat = "S"
	TableSeatW TableSeat = "W"
)

// Valid indicates whether the value is a known member of the TableSeat enum.
func (e TableSeat) Valid() bool {
	switch e {
	case TableSeatE:
		return true
	case TableSeatN:
		return true
	case TableSeatS:
		return true
	case TableSeatW:
		return true
	default:
		return false
	}
}

// Defines values for TableState.
const (
	ACTIVE        TableState = "ACTIVE"
	BETWEENBOARDS TableState = "BETWEEN_BOARDS"
	FINISHED      TableState = "FINISHED"
	PAUSED        TableState = "PAUSED"
	WAITING       TableState = "WAITING"
)

// Valid indicates whether the value is a known member of the TableState enum.
func (e TableState) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case BETWEENBOARDS:
		return true
	case FINISHED:
		return true
	case PAUSED:
		return true
	case WAITING:
		return true
	default:
		return false
	}
}

// AnalysisHand defines model for AnalysisHand.
type AnalysisHand struct {
	C  AnalysisTricks `json:"C"`
	D  AnalysisTricks `json:"D"`
	H  AnalysisTricks `json:"H"`
	NT AnalysisTricks `json:"NT"`
	S  AnalysisTricks `json:"S"`
}

// AnalysisResult defines model for AnalysisResult.
type AnalysisResult struct {
	DoubleDummyTable struct {
		E AnalysisHand `json:"E"`
		N AnalysisHand `json:"N"`
		S AnalysisHand `json:"S"`
		W AnalysisHand `json:"W"`
	} `json:"doubleDummyTable"`

	// MakeableContracts Maximum makeable undoubled level for each declarer and strain that can take at least seven tricks.
	MakeableContracts []struct {
		Declarer TableSeat      `json:"declarer"`
		Level    int            `json:"level"`
		Strain   AnalysisStrain `json:"strain"`
	} `json:"makeableContracts"`
	Par struct {
		Contracts []struct {
			Declarers   []TableSeat    `json:"declarers"`
			Doubled     bool           `json:"doubled"`
			Level       int            `json:"level"`
			OverTricks  int            `json:"overTricks"`
			Strain      AnalysisStrain `json:"strain"`
			UnderTricks int            `json:"underTricks"`
		} `json:"contracts"`
		ScoreNS int `json:"scoreNS"`
	} `json:"par"`
	SolverVersion AnalysisResultSolverVersion `json:"solverVersion"`
}

// AnalysisResultSolverVersion defines model for AnalysisResult.SolverVersion.
type AnalysisResultSolverVersion string

// AnalysisStrain defines model for AnalysisStrain.
type AnalysisStrain string

// AnalysisTricks defines model for AnalysisTricks.
type AnalysisTricks = int

// BoardAnalysis defines model for BoardAnalysis.
type BoardAnalysis struct {
	Analysis AnalysisResult     `json:"analysis"`
	BoardId  openapi_types.UUID `json:"boardId"`
	Metadata struct {
		Dealer        TableSeat                          `json:"dealer"`
		Number        int                                `json:"number"`
		Vulnerability BoardAnalysisMetadataVulnerability `json:"vulnerability"`
	} `json:"metadata"`
	Provenance struct {
		Reference *openapi_types.UUID         `json:"reference,omitempty"`
		Type      BoardAnalysisProvenanceType `json:"type"`
		Version   string                      `json:"version"`
	} `json:"provenance"`
}

// BoardAnalysisMetadataVulnerability defines model for BoardAnalysis.Metadata.Vulnerability.
type BoardAnalysisMetadataVulnerability string

// BoardAnalysisProvenanceType defines model for BoardAnalysis.Provenance.Type.
type BoardAnalysisProvenanceType string

// BoardReplay defines model for BoardReplay.
type BoardReplay struct {
	BoardId  openapi_types.UUID `json:"boardId"`
	FullDeal ReplayDeal         `json:"fullDeal"`
	Game     ReplayGame         `json:"game"`
}

// CreateGuestSessionRequest defines model for CreateGuestSessionRequest.
type CreateGuestSessionRequest struct {
	Nickname string `json:"nickname"`
}

// CreateTableResponse defines model for CreateTableResponse.
type CreateTableResponse struct {
	InviteCode string    `json:"inviteCode"`
	Table      TableView `json:"table"`
}

// GuestCredentials defines model for GuestCredentials.
type GuestCredentials struct {
	AccessExpiresAt  time.Time          `json:"accessExpiresAt"`
	AccessToken      string             `json:"accessToken"`
	DeviceCredential string             `json:"deviceCredential"`
	Nickname         string             `json:"nickname"`
	SessionId        openapi_types.UUID `json:"sessionId"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// PositionAnalysis defines model for PositionAnalysis.
type PositionAnalysis struct {
	BoardId openapi_types.UUID `json:"boardId"`
	Cards   []struct {
		Card   ReplayCard `json:"card"`
		Tricks int        `json:"tricks"`
	} `json:"cards"`
	PositionKey string    `json:"positionKey"`
	Turn        TableSeat `json:"turn"`
}

// Problem defines model for Problem.
type Problem struct {
	Code       *string `json:"code,omitempty"`
	MessageKey *string `json:"messageKey,omitempty"`
	RequestId  *string `json:"requestId,omitempty"`
	Retryable  *bool   `json:"retryable,omitempty"`
	Status     int     `json:"status"`
	Title      string  `json:"title"`
	Type       string  `json:"type"`
}

// RealtimeTicket defines model for RealtimeTicket.
type RealtimeTicket struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Ticket    string    `json:"ticket"`
}

// RefreshGuestSessionRequest defines model for RefreshGuestSessionRequest.
type RefreshGuestSessionRequest struct {
	DeviceCredential string `json:"deviceCredential"`
}

// ReplayAuction defines model for ReplayAuction.
type ReplayAuction struct {
	Calls []struct {
		Call ReplayCall `json:"call"`
		Seat TableSeat  `json:"seat"`
	} `json:"calls"`
	Complete  bool            `json:"complete"`
	Contract  *ReplayContract `json:"contract,omitempty"`
	Dealer    TableSeat       `json:"dealer"`
	PassedOut bool            `json:"passedOut"`
	Turn      *TableSeat      `json:"turn,omitempty"`
}

// ReplayCall defines model for ReplayCall.
type ReplayCall struct {
	Kind   ReplayCallKind    `json:"kind"`
	Level  *int              `json:"level,omitempty"`
	Strain *ReplayCallStrain `json:"strain,omitempty"`
}

// ReplayCallKind defines model for ReplayCall.Kind.
type ReplayCallKind string

// ReplayCallStrain defines model for ReplayCall.Strain.
type ReplayCallStrain string

// ReplayCard defines model for ReplayCard.
type ReplayCard struct {
	Rank ReplayCardRank `json:"rank"`
	Suit ReplayCardSuit `json:"suit"`
}

// ReplayCardRank defines model for ReplayCard.Rank.
type ReplayCardRank string

// ReplayCardSuit defines model for ReplayCard.Suit.
type ReplayCardSuit string

// ReplayContract defines model for ReplayContract.
type ReplayContract struct {
	Declarer ReplayContractDeclarer `json:"declarer"`
	Doubling ReplayContractDoubling `json:"doubling"`
	Level    int                    `json:"level"`
	Strain   ReplayContractStrain   `json:"strain"`
}

// ReplayContractDeclarer defines model for ReplayContract.Declarer.
type ReplayContractDeclarer string

// ReplayContractDoubling defines model for ReplayContract.Doubling.
type ReplayContractDoubling string

// ReplayContractStrain defines model for ReplayContract.Strain.
type ReplayContractStrain string

// ReplayDeal defines model for ReplayDeal.
type ReplayDeal struct {
	East  *[]ReplayCard `json:"east"`
	North *[]ReplayCard `json:"north"`
	South *[]ReplayCard `json:"south"`
	West  *[]ReplayCard `json:"west"`
}

// ReplayGame defines model for ReplayGame.
type ReplayGame struct {
	Auction ReplayAuction `json:"auction"`
	Board   struct {
		Dealer        TableSeat                    `json:"dealer"`
		Number        int                          `json:"number"`
		Vulnerability ReplayGameBoardVulnerability `json:"vulnerability"`
	} `json:"board"`
	Claimed         bool            `json:"claimed"`
	CompletedTricks *[]ReplayTrick  `json:"completedTricks"`
	CurrentTrick    ReplayTrick     `json:"currentTrick"`
	Deal            ReplayDeal      `json:"deal"`
	DummyRevealed   bool            `json:"dummyRevealed"`
	Phase           ReplayGamePhase `json:"phase"`
	Result          ReplayResult    `json:"result"`
	RulesetVersion  string          `json:"rulesetVersion"`
	TricksEW        AnalysisTricks  `json:"tricksEW"`
	TricksNS        AnalysisTricks  `json:"tricksNS"`
	Turn            *TableSeat      `json:"turn,omitempty"`
}

// ReplayGameBoardVulnerability defines model for ReplayGame.Board.Vulnerability.
type ReplayGameBoardVulnerability string

// ReplayGamePhase defines model for ReplayGame.Phase.
type ReplayGamePhase string

// ReplayResult defines model for ReplayResult.
type ReplayResult struct {
	Contract       *ReplayContract           `json:"contract,omitempty"`
	PassedOut      bool                      `json:"passedOut"`
	RulesetVersion string                    `json:"rulesetVersion"`
	ScoreNS        int                       `json:"scoreNS"`
	TricksDeclarer int                       `json:"tricksDeclarer"`
	TricksEW       int                       `json:"tricksEW"`
	TricksNS       int                       `json:"tricksNS"`
	Vulnerability  ReplayResultVulnerability `json:"vulnerability"`
}

// ReplayResultVulnerability defines model for ReplayResult.Vulnerability.
type ReplayResultVulnerability string

// ReplayTrick defines model for ReplayTrick.
type ReplayTrick struct {
	Leader ReplayTrickLeader `json:"leader"`
	Plays  *[]struct {
		Card ReplayCard `json:"card"`
		Seat TableSeat  `json:"seat"`
	} `json:"plays"`
	Winner *TableSeat `json:"winner,omitempty"`
}

// ReplayTrickLeader defines model for ReplayTrick.Leader.
type ReplayTrickLeader string

// TableParticipant defines model for TableParticipant.
type TableParticipant struct {
	Id       openapi_types.UUID `json:"id"`
	IsBot    bool               `json:"isBot"`
	Nickname string             `json:"nickname"`
	Role     TableRole          `json:"role"`
}

// TablePreview defines model for TablePreview.
type TablePreview struct {
	Capacity         int        `json:"capacity"`
	Locked           bool       `json:"locked"`
	ParticipantCount int        `json:"participantCount"`
	State            TableState `json:"state"`
}

// TableRole defines model for TableRole.
type TableRole string

// TableSeat defines model for TableSeat.
type TableSeat string

// TableSeatAssignment defines model for TableSeatAssignment.
type TableSeatAssignment struct {
	ControllerEpoch int64              `json:"controllerEpoch"`
	IsBot           *bool              `json:"isBot,omitempty"`
	ParticipantId   openapi_types.UUID `json:"participantId"`
	Ready           bool               `json:"ready"`
}

// TableState defines model for TableState.
type TableState string

// TableView defines model for TableView.
type TableView struct {
	BoardId             *openapi_types.UUID            `json:"boardId,omitempty"`
	BoardNumber         int                            `json:"boardNumber"`
	LastSeq             int64                          `json:"lastSeq"`
	Locked              bool                           `json:"locked"`
	Participants        []TableParticipant             `json:"participants"`
	Revision            int64                          `json:"revision"`
	Seats               map[string]TableSeatAssignment `json:"seats"`
	State               TableState                     `json:"state"`
	TableId             openapi_types.UUID             `json:"tableId"`
	ViewerParticipantId openapi_types.UUID             `json:"viewerParticipantId"`
	ViewerRole          TableRole                      `json:"viewerRole"`
	ViewerSeat          *TableSeat                     `json:"viewerSeat,omitempty"`
}

// InviteCode defines model for InviteCode.
type InviteCode = string

// TableId defines model for TableId.
type TableId = openapi_types.UUID

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse = Problem

// AnalyzeCompletedBoardParams defines parameters for AnalyzeCompletedBoard.
type AnalyzeCompletedBoardParams struct {
	// PositionKey Live table revision as a decimal string, or replay request identity when step is present.
	PositionKey *string `form:"positionKey,omitempty" json:"positionKey,omitempty"`

	// Step Number of played cards in a completed board, requires positionKey.
	Step *int `form:"step,omitempty" json:"step,omitempty"`
}

// AnalyzeCompletedBoard200JSONResponseBody defines parameters for AnalyzeCompletedBoard.
type AnalyzeCompletedBoard200JSONResponseBody struct {
	union json.RawMessage
}

// CreateGuestSessionJSONRequestBody defines body for CreateGuestSession for application/json ContentType.
type CreateGuestSessionJSONRequestBody = CreateGuestSessionRequest

// RefreshGuestSessionJSONRequestBody defines body for RefreshGuestSession for application/json ContentType.
type RefreshGuestSessionJSONRequestBody = RefreshGuestSessionRequest

// AsBoardAnalysis returns the union data inside the AnalyzeCompletedBoard200JSONResponseBody as a BoardAnalysis
func (t AnalyzeCompletedBoard200JSONResponseBody) AsBoardAnalysis() (BoardAnalysis, error) {
	var body BoardAnalysis
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBoardAnalysis overwrites any union data inside the AnalyzeCompletedBoard200JSONResponseBody as the provided BoardAnalysis
func (t *AnalyzeCompletedBoard200JSONResponseBody) FromBoardAnalysis(v BoardAnalysis) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBoardAnalysis performs a merge with any union data inside the AnalyzeCompletedBoard200JSONResponseBody, using the provided BoardAnalysis
func (t *AnalyzeCompletedBoard200JSONResponseBody) MergeBoardAnalysis(v BoardAnalysis) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPositionAnalysis returns the union data inside the AnalyzeCompletedBoard200JSONResponseBody as a PositionAnalysis
func (t AnalyzeCompletedBoard200JSONResponseBody) AsPositionAnalysis() (PositionAnalysis, error) {
	var body PositionAnalysis
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPositionAnalysis overwrites any union data inside the AnalyzeCompletedBoard200JSONResponseBody as the provided PositionAnalysis
func (t *AnalyzeCompletedBoard200JSONResponseBody) FromPositionAnalysis(v PositionAnalysis) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePositionAnalysis performs a merge with any union data inside the AnalyzeCompletedBoard200JSONResponseBody, using the provided PositionAnalysis
func (t *AnalyzeCompletedBoard200JSONResponseBody) MergePositionAnalysis(v PositionAnalysis) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnalyzeCompletedBoard200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnalyzeCompletedBoard200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
