// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AnalysisResultSolverVersion.
const (
	Dds2908d75755 AnalysisResultSolverVersion = "dds-2.9.0-8d75755"
)

// Valid indicates whether the value is a known member of the AnalysisResultSolverVersion enum.
func (e AnalysisResultSolverVersion) Valid() bool {
	switch e {
	case Dds2908d75755:
		return true
	default:
		return false
	}
}

// Defines values for AnalysisStrain.
const (
	AnalysisStrainC  AnalysisStrain = "C"
	AnalysisStrainD  AnalysisStrain = "D"
	AnalysisStrainH  AnalysisStrain = "H"
	AnalysisStrainNT AnalysisStrain = "NT"
	AnalysisStrainS  AnalysisStrain = "S"
)

// Valid indicates whether the value is a known member of the AnalysisStrain enum.
func (e AnalysisStrain) Valid() bool {
	switch e {
	case AnalysisStrainC:
		return true
	case AnalysisStrainD:
		return true
	case AnalysisStrainH:
		return true
	case AnalysisStrainNT:
		return true
	case AnalysisStrainS:
		return true
	default:
		return false
	}
}

// Defines values for BoardAnalysisMetadataVulnerability.
const (
	BOTH BoardAnalysisMetadataVulnerability = "BOTH"
	EW   BoardAnalysisMetadataVulnerability = "EW"
	NONE BoardAnalysisMetadataVulnerability = "NONE"
	NS   BoardAnalysisMetadataVulnerability = "NS"
)

// Valid indicates whether the value is a known member of the BoardAnalysisMetadataVulnerability enum.
func (e BoardAnalysisMetadataVulnerability) Valid() bool {
	switch e {
	case BOTH:
		return true
	case EW:
		return true
	case NONE:
		return true
	case NS:
		return true
	default:
		return false
	}
}

// Defines values for BoardAnalysisProvenanceType.
const (
	Constraint    BoardAnalysisProvenanceType = "constraint"
	Deterministic BoardAnalysisProvenanceType = "deterministic"
	Prepared      BoardAnalysisProvenanceType = "prepared"
	SecureRandom  BoardAnalysisProvenanceType = "secure_random"
)

// Valid indicates whether the value is a known member of the BoardAnalysisProvenanceType enum.
func (e BoardAnalysisProvenanceType) Valid() bool {
	switch e {
	case Constraint:
		return true
	case Deterministic:
		return true
	case Prepared:
		return true
	case SecureRandom:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Ready       HealthResponseStatus = "ready"
	Unavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Ready:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for TableRole.
const (
	OWNER       TableRole = "OWNER"
	PARTICIPANT TableRole = "PARTICIPANT"
)

// Valid indicates whether the value is a known member of the TableRole enum.
func (e TableRole) Valid() bool {
	switch e {
	case OWNER:
		return true
	case PARTICIPANT:
		return true
	default:
		return false
	}
}

// Defines values for TableSeat.
const (
	TableSeatE TableSeat = "E"
	TableSeatN TableSeat = "N"
	TableSeatS TableSeat = "S"
	TableSeatW TableSeat = "W"
)

// Valid indicates whether the value is a known member of the TableSeat enum.
func (e TableSeat) Valid() bool {
	switch e {
	case TableSeatE:
		return true
	case TableSeatN:
		return true
	case TableSeatS:
		return true
	case TableSeatW:
		return true
	default:
		return false
	}
}

// Defines values for TableState.
const (
	ACTIVE        TableState = "ACTIVE"
	BETWEENBOARDS TableState = "BETWEEN_BOARDS"
	FINISHED      TableState = "FINISHED"
	PAUSED        TableState = "PAUSED"
	WAITING       TableState = "WAITING"
)

// Valid indicates whether the value is a known member of the TableState enum.
func (e TableState) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case BETWEENBOARDS:
		return true
	case FINISHED:
		return true
	case PAUSED:
		return true
	case WAITING:
		return true
	default:
		return false
	}
}

// AnalysisHand defines model for AnalysisHand.
type AnalysisHand struct {
	C  AnalysisTricks `json:"C"`
	D  AnalysisTricks `json:"D"`
	H  AnalysisTricks `json:"H"`
	NT AnalysisTricks `json:"NT"`
	S  AnalysisTricks `json:"S"`
}

// AnalysisResult defines model for AnalysisResult.
type AnalysisResult struct {
	DoubleDummyTable struct {
		E AnalysisHand `json:"E"`
		N AnalysisHand `json:"N"`
		S AnalysisHand `json:"S"`
		W AnalysisHand `json:"W"`
	} `json:"doubleDummyTable"`

	// MakeableContracts Maximum makeable undoubled level for each declarer and strain that can take at least seven tricks.
	MakeableContracts []struct {
		Declarer TableSeat      `json:"declarer"`
		Level    int            `json:"level"`
		Strain   AnalysisStrain `json:"strain"`
	} `json:"makeableContracts"`
	Par struct {
		Contracts []struct {
			Declarers   []TableSeat    `json:"declarers"`
			Doubled     bool           `json:"doubled"`
			Level       int            `json:"level"`
			OverTricks  int            `json:"overTricks"`
			Strain      AnalysisStrain `json:"strain"`
			UnderTricks int            `json:"underTricks"`
		} `json:"contracts"`
		ScoreNS int `json:"scoreNS"`
	} `json:"par"`
	SolverVersion AnalysisResultSolverVersion `json:"solverVersion"`
}

// AnalysisResultSolverVersion defines model for AnalysisResult.SolverVersion.
type AnalysisResultSolverVersion string

// AnalysisStrain defines model for AnalysisStrain.
type AnalysisStrain string

// AnalysisTricks defines model for AnalysisTricks.
type AnalysisTricks = int

// BoardAnalysis defines model for BoardAnalysis.
type BoardAnalysis struct {
	Analysis AnalysisResult     `json:"analysis"`
	BoardId  openapi_types.UUID `json:"boardId"`
	Metadata struct {
		Dealer        TableSeat                          `json:"dealer"`
		Number        int                                `json:"number"`
		Vulnerability BoardAnalysisMetadataVulnerability `json:"vulnerability"`
	} `json:"metadata"`
	Provenance struct {
		Reference *openapi_types.UUID         `json:"reference,omitempty"`
		Type      BoardAnalysisProvenanceType `json:"type"`
		Version   string                      `json:"version"`
	} `json:"provenance"`
}

// BoardAnalysisMetadataVulnerability defines model for BoardAnalysis.Metadata.Vulnerability.
type BoardAnalysisMetadataVulnerability string

// BoardAnalysisProvenanceType defines model for BoardAnalysis.Provenance.Type.
type BoardAnalysisProvenanceType string

// CreateGuestSessionRequest defines model for CreateGuestSessionRequest.
type CreateGuestSessionRequest struct {
	Nickname string `json:"nickname"`
}

// CreateTableResponse defines model for CreateTableResponse.
type CreateTableResponse struct {
	InviteCode string    `json:"inviteCode"`
	Table      TableView `json:"table"`
}

// GuestCredentials defines model for GuestCredentials.
type GuestCredentials struct {
	AccessExpiresAt  time.Time          `json:"accessExpiresAt"`
	AccessToken      string             `json:"accessToken"`
	DeviceCredential string             `json:"deviceCredential"`
	Nickname         string             `json:"nickname"`
	SessionId        openapi_types.UUID `json:"sessionId"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Problem defines model for Problem.
type Problem struct {
	Code       *string `json:"code,omitempty"`
	MessageKey *string `json:"messageKey,omitempty"`
	RequestId  *string `json:"requestId,omitempty"`
	Retryable  *bool   `json:"retryable,omitempty"`
	Status     int     `json:"status"`
	Title      string  `json:"title"`
	Type       string  `json:"type"`
}

// RealtimeTicket defines model for RealtimeTicket.
type RealtimeTicket struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Ticket    string    `json:"ticket"`
}

// RefreshGuestSessionRequest defines model for RefreshGuestSessionRequest.
type RefreshGuestSessionRequest struct {
	DeviceCredential string `json:"deviceCredential"`
}

// TableParticipant defines model for TableParticipant.
type TableParticipant struct {
	Id       openapi_types.UUID `json:"id"`
	IsBot    bool               `json:"isBot"`
	Nickname string             `json:"nickname"`
	Role     TableRole          `json:"role"`
}

// TablePreview defines model for TablePreview.
type TablePreview struct {
	Capacity         int        `json:"capacity"`
	Locked           bool       `json:"locked"`
	ParticipantCount int        `json:"participantCount"`
	State            TableState `json:"state"`
}

// TableRole defines model for TableRole.
type TableRole string

// TableSeat defines model for TableSeat.
type TableSeat string

// TableSeatAssignment defines model for TableSeatAssignment.
type TableSeatAssignment struct {
	ControllerEpoch int64              `json:"controllerEpoch"`
	IsBot           *bool              `json:"isBot,omitempty"`
	ParticipantId   openapi_types.UUID `json:"participantId"`
	Ready           bool               `json:"ready"`
}

// TableState defines model for TableState.
type TableState string

// TableView defines model for TableView.
type TableView struct {
	BoardId             *openapi_types.UUID            `json:"boardId,omitempty"`
	BoardNumber         int                            `json:"boardNumber"`
	LastSeq             int64                          `json:"lastSeq"`
	Locked              bool                           `json:"locked"`
	Participants        []TableParticipant             `json:"participants"`
	Revision            int64                          `json:"revision"`
	Seats               map[string]TableSeatAssignment `json:"seats"`
	State               TableState                     `json:"state"`
	TableId             openapi_types.UUID             `json:"tableId"`
	ViewerParticipantId openapi_types.UUID             `json:"viewerParticipantId"`
	ViewerRole          TableRole                      `json:"viewerRole"`
	ViewerSeat          *TableSeat                     `json:"viewerSeat,omitempty"`
}

// InviteCode defines model for InviteCode.
type InviteCode = string

// TableId defines model for TableId.
type TableId = openapi_types.UUID

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse = Problem

// CreateGuestSessionJSONRequestBody defines body for CreateGuestSession for application/json ContentType.
type CreateGuestSessionJSONRequestBody = CreateGuestSessionRequest

// RefreshGuestSessionJSONRequestBody defines body for RefreshGuestSession for application/json ContentType.
type RefreshGuestSessionJSONRequestBody = RefreshGuestSessionRequest
