// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_record.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompactedBoardEvents = `-- name: DeleteCompactedBoardEvents :exec
DELETE FROM bridgeyok.game_events e USING bridgeyok.board_records r
WHERE r.board_id = $1 AND e.table_id = r.table_id
  AND e.seq BETWEEN r.first_seq AND r.last_seq
`

func (q *Queries) DeleteCompactedBoardEvents(ctx context.Context, boardID string) error {
	_, err := q.db.Exec(ctx, deleteCompactedBoardEvents, boardID)
	return err
}

const deleteHistoryBoardLabel = `-- name: DeleteHistoryBoardLabel :execrows
DELETE FROM bridgeyok.history_board_labels label
WHERE label.session_id = $1
  AND label.board_id = $2
  AND EXISTS (
      SELECT 1
      FROM bridgeyok.board_seat_attributions attribution
      JOIN bridgeyok.table_participants participant
        ON participant.table_id = attribution.table_id
       AND participant.id = attribution.occupant_id
       AND participant.session_id = $1
      WHERE attribution.board_id = $2
  )
`

type DeleteHistoryBoardLabelParams struct {
	SessionID string `json:"session_id"`
	BoardID   string `json:"board_id"`
}

func (q *Queries) DeleteHistoryBoardLabel(ctx context.Context, arg DeleteHistoryBoardLabelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHistoryBoardLabel, arg.SessionID, arg.BoardID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBoardRecord = `-- name: FindBoardRecord :one
SELECT r.record FROM bridgeyok.board_records r
WHERE r.board_id = $1
  AND NOT EXISTS (
      SELECT 1 FROM bridgeyok.match_rooms mr
      JOIN bridgeyok.team_matches m ON m.id = mr.match_id
      WHERE mr.table_id = r.table_id AND m.status <> 'COMPLETE'
  )
  AND EXISTS (SELECT 1 FROM bridgeyok.table_participants p
              WHERE p.table_id = r.table_id AND p.session_id = $2)
`

type FindBoardRecordParams struct {
	BoardID   string `json:"board_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) FindBoardRecord(ctx context.Context, arg FindBoardRecordParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, findBoardRecord, arg.BoardID, arg.SessionID)
	var record []byte
	err := row.Scan(&record)
	return record, err
}

const insertBoardRecord = `-- name: InsertBoardRecord :execrows
INSERT INTO bridgeyok.board_records(board_id, table_id, first_seq, last_seq, final_revision, record, compacted_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
ON CONFLICT (board_id) DO UPDATE SET record = EXCLUDED.record
WHERE board_records.record = EXCLUDED.record
  AND board_records.table_id = EXCLUDED.table_id
  AND board_records.first_seq = EXCLUDED.first_seq
  AND board_records.last_seq = EXCLUDED.last_seq
  AND board_records.final_revision = EXCLUDED.final_revision
`

type InsertBoardRecordParams struct {
	BoardID       string             `json:"board_id"`
	TableID       string             `json:"table_id"`
	FirstSeq      int64              `json:"first_seq"`
	LastSeq       int64              `json:"last_seq"`
	FinalRevision int64              `json:"final_revision"`
	Record        []byte             `json:"record"`
	CompactedAt   pgtype.Timestamptz `json:"compacted_at"`
}

func (q *Queries) InsertBoardRecord(ctx context.Context, arg InsertBoardRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBoardRecord,
		arg.BoardID,
		arg.TableID,
		arg.FirstSeq,
		arg.LastSeq,
		arg.FinalRevision,
		arg.Record,
		arg.CompactedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBoardRecordEvents = `-- name: ListBoardRecordEvents :many
SELECT e.seq, e.revision, e.event_type, e.payload, e.occurred_at
FROM bridgeyok.game_events e
WHERE e.table_id = $1
  AND e.seq >= (SELECT started.seq FROM bridgeyok.game_events started
              WHERE started.table_id = $1 AND started.event_type = 'BOARD_STARTED'
                AND started.payload->>'boardId' = $2::text)
  AND e.seq <= $3
ORDER BY e.seq
`

type ListBoardRecordEventsParams struct {
	TableID string `json:"table_id"`
	BoardID string `json:"board_id"`
	LastSeq int64  `json:"last_seq"`
}

type ListBoardRecordEventsRow struct {
	Seq        int64              `json:"seq"`
	Revision   int64              `json:"revision"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListBoardRecordEvents(ctx context.Context, arg ListBoardRecordEventsParams) ([]ListBoardRecordEventsRow, error) {
	rows, err := q.db.Query(ctx, listBoardRecordEvents, arg.TableID, arg.BoardID, arg.LastSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardRecordEventsRow{}
	for rows.Next() {
		var i ListBoardRecordEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Revision,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryBoards = `-- name: ListHistoryBoards :many
SELECT b.id,
       b.table_id,
       b.board_number,
       b.result,
       b.completed_at,
       board_label.label,
       jsonb_object_agg(
           attribution.seat,
           jsonb_build_object(
               'id', attribution.occupant_id,
               'nickname', attribution.nickname,
               'isBot', attribution.is_bot
           ) ORDER BY attribution.seat
       ) AS lineup,
       viewer_seat.seat AS viewer_seat,
       match_room_board.match_id,
       COALESCE(team_match.status, '') AS match_status,
       COALESCE(match_room_board.room, '') AS match_room,
       COALESCE(CASE
           WHEN match_assignment.room = 'OPEN' AND match_assignment.seat IN ('N', 'S') THEN 'A'
           WHEN match_assignment.room = 'CLOSED' AND match_assignment.seat IN ('E', 'W') THEN 'A'
           WHEN match_assignment.match_id IS NOT NULL THEN 'B'
           ELSE NULL
       END, '') AS team,
       comparison.team_a_imp
FROM bridgeyok.boards b
JOIN bridgeyok.board_seat_attributions attribution
  ON attribution.board_id = b.id
LEFT JOIN LATERAL (
    SELECT board_attribution.seat
    FROM bridgeyok.board_seat_attributions board_attribution
    JOIN bridgeyok.table_participants participant
      ON participant.table_id = b.table_id
     AND participant.id = board_attribution.occupant_id
     AND participant.session_id = $1
    WHERE board_attribution.board_id = b.id
    LIMIT 1
) viewer_seat ON true
LEFT JOIN bridgeyok.match_room_boards match_room_board
  ON match_room_board.table_board_id = b.id
LEFT JOIN bridgeyok.team_matches team_match
  ON team_match.id = match_room_board.match_id
LEFT JOIN bridgeyok.match_assignments match_assignment
  ON match_assignment.match_id = match_room_board.match_id
 AND match_assignment.session_id = $1
LEFT JOIN bridgeyok.match_comparisons comparison
  ON comparison.match_id = match_room_board.match_id
 AND comparison.board_id = match_room_board.board_id
LEFT JOIN bridgeyok.history_board_labels board_label
  ON board_label.board_id = b.id
 AND board_label.session_id = $1
WHERE b.status IN ('SCORED', 'PASSED_OUT')
  AND b.completed_at IS NOT NULL
  AND viewer_seat.seat IS NOT NULL
  AND EXISTS (
      SELECT 1
      FROM bridgeyok.table_participants participant
      WHERE participant.table_id = b.table_id
        AND participant.session_id = $1
  )
  AND (
      $2::timestamptz IS NULL
      OR (b.completed_at, b.id) < ($2::timestamptz, $3::uuid)
  )
  AND (
      NULLIF(trim($4::text), '') IS NULL
      OR board_label.label ILIKE '%' || trim($4::text) || '%'
      OR to_char(b.completed_at AT TIME ZONE 'Asia/Jakarta', 'YYYY-MM-DD') ILIKE '%' || trim($4::text) || '%'
      OR to_char(b.completed_at AT TIME ZONE 'Asia/Jakarta', 'DD/MM/YYYY') ILIKE '%' || trim($4::text) || '%'
      OR to_char(b.completed_at AT TIME ZONE 'Asia/Jakarta', 'DD-MM-YYYY') ILIKE '%' || trim($4::text) || '%'
      OR b.result::text ILIKE '%' || trim($4::text) || '%'
      OR lower(regexp_replace(
          CASE
              WHEN b.result->>'passedOut' = 'true' THEN 'passedout'
              ELSE concat(
                  b.result->'contract'->>'level',
                  CASE b.result->'contract'->>'strain'
                      WHEN 'NT' THEN 'NT'
                      ELSE b.result->'contract'->>'strain'
                  END,
                  CASE b.result->'contract'->>'doubling'
                      WHEN 'DOUBLED' THEN 'X'
                      WHEN 'REDOUBLED' THEN 'XX'
                      ELSE ''
                  END,
                  b.result->'contract'->>'declarer',
                  CASE
                      WHEN (b.result->>'tricksDeclarer')::integer - (6 + (b.result->'contract'->>'level')::integer) = 0 THEN '='
                      WHEN (b.result->>'tricksDeclarer')::integer - (6 + (b.result->'contract'->>'level')::integer) > 0 THEN '+' || ((b.result->>'tricksDeclarer')::integer - (6 + (b.result->'contract'->>'level')::integer))::text
                      ELSE ((b.result->>'tricksDeclarer')::integer - (6 + (b.result->'contract'->>'level')::integer))::text
                  END
              )
          END,
          '\s+', '', 'g'
      )) LIKE '%' || lower(regexp_replace(
          replace(replace(replace(replace(trim($4::text), '♣', 'C'), '♦', 'D'), '♥', 'H'), '♠', 'S'),
          '\s+', '', 'g'
      )) || '%'
  )
GROUP BY b.id, b.table_id, b.board_number, b.result, b.completed_at,
         board_label.label, viewer_seat.seat, match_room_board.match_id, team_match.status,
         match_room_board.room, match_assignment.room, match_assignment.seat,
         match_assignment.match_id, comparison.team_a_imp
ORDER BY b.completed_at DESC, b.id DESC
LIMIT $5
`

type ListHistoryBoardsParams struct {
	SessionID string             `json:"session_id"`
	CursorAt  pgtype.Timestamptz `json:"cursor_at"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	Search    string             `json:"search"`
	PageLimit int32              `json:"page_limit"`
}

type ListHistoryBoardsRow struct {
	ID          string             `json:"id"`
	TableID     string             `json:"table_id"`
	BoardNumber int32              `json:"board_number"`
	Result      []byte             `json:"result"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Label       *string            `json:"label"`
	Lineup      []byte             `json:"lineup"`
	ViewerSeat  string             `json:"viewer_seat"`
	MatchID     pgtype.UUID        `json:"match_id"`
	MatchStatus string             `json:"match_status"`
	MatchRoom   string             `json:"match_room"`
	Team        interface{}        `json:"team"`
	TeamAImp    *int32             `json:"team_a_imp"`
}

func (q *Queries) ListHistoryBoards(ctx context.Context, arg ListHistoryBoardsParams) ([]ListHistoryBoardsRow, error) {
	rows, err := q.db.Query(ctx, listHistoryBoards,
		arg.SessionID,
		arg.CursorAt,
		arg.CursorID,
		arg.Search,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryBoardsRow{}
	for rows.Next() {
		var i ListHistoryBoardsRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.BoardNumber,
			&i.Result,
			&i.CompletedAt,
			&i.Label,
			&i.Lineup,
			&i.ViewerSeat,
			&i.MatchID,
			&i.MatchStatus,
			&i.MatchRoom,
			&i.Team,
			&i.TeamAImp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadBoardRecord = `-- name: LoadBoardRecord :one
SELECT board_id, table_id, first_seq, last_seq, final_revision, record, compacted_at FROM bridgeyok.board_records WHERE board_id = $1
`

func (q *Queries) LoadBoardRecord(ctx context.Context, boardID string) (BridgeyokBoardRecord, error) {
	row := q.db.QueryRow(ctx, loadBoardRecord, boardID)
	var i BridgeyokBoardRecord
	err := row.Scan(
		&i.BoardID,
		&i.TableID,
		&i.FirstSeq,
		&i.LastSeq,
		&i.FinalRevision,
		&i.Record,
		&i.CompactedAt,
	)
	return i, err
}

const loadBoardSource = `-- name: LoadBoardSource :one
SELECT source_record FROM bridgeyok.board_deals WHERE board_id = $1
`

func (q *Queries) LoadBoardSource(ctx context.Context, boardID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadBoardSource, boardID)
	var source_record []byte
	err := row.Scan(&source_record)
	return source_record, err
}

const upsertHistoryBoardLabel = `-- name: UpsertHistoryBoardLabel :execrows
INSERT INTO bridgeyok.history_board_labels (session_id, board_id, label, updated_at)
SELECT $1, $2, $3, $4
WHERE EXISTS (
    SELECT 1
    FROM bridgeyok.board_seat_attributions attribution
    JOIN bridgeyok.table_participants participant
      ON participant.table_id = attribution.table_id
     AND participant.id = attribution.occupant_id
     AND participant.session_id = $1
    WHERE attribution.board_id = $2
)
ON CONFLICT (session_id, board_id) DO UPDATE SET
    label = EXCLUDED.label,
    updated_at = EXCLUDED.updated_at
`

type UpsertHistoryBoardLabelParams struct {
	SessionID string             `json:"session_id"`
	BoardID   string             `json:"board_id"`
	Label     string             `json:"label"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertHistoryBoardLabel(ctx context.Context, arg UpsertHistoryBoardLabelParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertHistoryBoardLabel,
		arg.SessionID,
		arg.BoardID,
		arg.Label,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
