// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_record.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompactedBoardEvents = `-- name: DeleteCompactedBoardEvents :exec
DELETE FROM bridgeyok.game_events e USING bridgeyok.board_records r
WHERE r.board_id = $1 AND e.table_id = r.table_id
  AND e.seq BETWEEN r.first_seq AND r.last_seq
`

func (q *Queries) DeleteCompactedBoardEvents(ctx context.Context, boardID string) error {
	_, err := q.db.Exec(ctx, deleteCompactedBoardEvents, boardID)
	return err
}

const findBoardRecord = `-- name: FindBoardRecord :one
SELECT r.record FROM bridgeyok.board_records r
WHERE r.board_id = $1
  AND EXISTS (SELECT 1 FROM bridgeyok.table_participants p
              WHERE p.table_id = r.table_id AND p.session_id = $2 AND p.left_at IS NULL)
`

type FindBoardRecordParams struct {
	BoardID   string `json:"board_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) FindBoardRecord(ctx context.Context, arg FindBoardRecordParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, findBoardRecord, arg.BoardID, arg.SessionID)
	var record []byte
	err := row.Scan(&record)
	return record, err
}

const insertBoardRecord = `-- name: InsertBoardRecord :execrows
INSERT INTO bridgeyok.board_records(board_id, table_id, first_seq, last_seq, final_revision, record, compacted_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
ON CONFLICT (board_id) DO UPDATE SET record = EXCLUDED.record
WHERE board_records.record = EXCLUDED.record
  AND board_records.table_id = EXCLUDED.table_id
  AND board_records.first_seq = EXCLUDED.first_seq
  AND board_records.last_seq = EXCLUDED.last_seq
  AND board_records.final_revision = EXCLUDED.final_revision
`

type InsertBoardRecordParams struct {
	BoardID       string             `json:"board_id"`
	TableID       string             `json:"table_id"`
	FirstSeq      int64              `json:"first_seq"`
	LastSeq       int64              `json:"last_seq"`
	FinalRevision int64              `json:"final_revision"`
	Record        []byte             `json:"record"`
	CompactedAt   pgtype.Timestamptz `json:"compacted_at"`
}

func (q *Queries) InsertBoardRecord(ctx context.Context, arg InsertBoardRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBoardRecord,
		arg.BoardID,
		arg.TableID,
		arg.FirstSeq,
		arg.LastSeq,
		arg.FinalRevision,
		arg.Record,
		arg.CompactedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBoardRecordEvents = `-- name: ListBoardRecordEvents :many
SELECT e.seq, e.revision, e.event_type, e.payload, e.occurred_at
FROM bridgeyok.game_events e
WHERE e.table_id = $1
  AND e.seq >= (SELECT started.seq FROM bridgeyok.game_events started
              WHERE started.table_id = $1 AND started.event_type = 'BOARD_STARTED'
                AND started.payload->>'boardId' = $2::text)
  AND e.seq <= $3
ORDER BY e.seq
`

type ListBoardRecordEventsParams struct {
	TableID string `json:"table_id"`
	BoardID string `json:"board_id"`
	LastSeq int64  `json:"last_seq"`
}

type ListBoardRecordEventsRow struct {
	Seq        int64              `json:"seq"`
	Revision   int64              `json:"revision"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListBoardRecordEvents(ctx context.Context, arg ListBoardRecordEventsParams) ([]ListBoardRecordEventsRow, error) {
	rows, err := q.db.Query(ctx, listBoardRecordEvents, arg.TableID, arg.BoardID, arg.LastSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardRecordEventsRow{}
	for rows.Next() {
		var i ListBoardRecordEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Revision,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadBoardRecord = `-- name: LoadBoardRecord :one
SELECT board_id, table_id, first_seq, last_seq, final_revision, record, compacted_at FROM bridgeyok.board_records WHERE board_id = $1
`

func (q *Queries) LoadBoardRecord(ctx context.Context, boardID string) (BridgeyokBoardRecord, error) {
	row := q.db.QueryRow(ctx, loadBoardRecord, boardID)
	var i BridgeyokBoardRecord
	err := row.Scan(
		&i.BoardID,
		&i.TableID,
		&i.FirstSeq,
		&i.LastSeq,
		&i.FinalRevision,
		&i.Record,
		&i.CompactedAt,
	)
	return i, err
}

const loadBoardSource = `-- name: LoadBoardSource :one
SELECT source_record FROM bridgeyok.board_deals WHERE board_id = $1
`

func (q *Queries) LoadBoardSource(ctx context.Context, boardID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadBoardSource, boardID)
	var source_record []byte
	err := row.Scan(&source_record)
	return source_record, err
}
