// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: command.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTableSeatsForSync = `-- name: DeleteTableSeatsForSync :exec
DELETE FROM bridgeyok.table_seats
WHERE table_id = $1
`

func (q *Queries) DeleteTableSeatsForSync(ctx context.Context, tableID string) error {
	_, err := q.db.Exec(ctx, deleteTableSeatsForSync, tableID)
	return err
}

const findProcessedCommand = `-- name: FindProcessedCommand :one
SELECT outcome
FROM bridgeyok.processed_commands
WHERE table_id = $1
  AND session_id = $2
  AND request_id = $3
`

type FindProcessedCommandParams struct {
	TableID   string `json:"table_id"`
	SessionID string `json:"session_id"`
	RequestID string `json:"request_id"`
}

func (q *Queries) FindProcessedCommand(ctx context.Context, arg FindProcessedCommandParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, findProcessedCommand, arg.TableID, arg.SessionID, arg.RequestID)
	var outcome []byte
	err := row.Scan(&outcome)
	return outcome, err
}

const insertGameEvent = `-- name: InsertGameEvent :exec
INSERT INTO bridgeyok.game_events (
    table_id,
    seq,
    revision,
    event_type,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertGameEventParams struct {
	TableID    string             `json:"table_id"`
	Seq        int64              `json:"seq"`
	Revision   int64              `json:"revision"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertGameEvent(ctx context.Context, arg InsertGameEventParams) error {
	_, err := q.db.Exec(ctx, insertGameEvent,
		arg.TableID,
		arg.Seq,
		arg.Revision,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertProcessedCommand = `-- name: InsertProcessedCommand :exec
INSERT INTO bridgeyok.processed_commands (
    table_id,
    session_id,
    request_id,
    command_name,
    outcome,
    revision,
    last_seq,
    processed_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type InsertProcessedCommandParams struct {
	TableID     string             `json:"table_id"`
	SessionID   string             `json:"session_id"`
	RequestID   string             `json:"request_id"`
	CommandName string             `json:"command_name"`
	Outcome     []byte             `json:"outcome"`
	Revision    int64              `json:"revision"`
	LastSeq     int64              `json:"last_seq"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertProcessedCommand(ctx context.Context, arg InsertProcessedCommandParams) error {
	_, err := q.db.Exec(ctx, insertProcessedCommand,
		arg.TableID,
		arg.SessionID,
		arg.RequestID,
		arg.CommandName,
		arg.Outcome,
		arg.Revision,
		arg.LastSeq,
		arg.ProcessedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertTableSeatForSync = `-- name: InsertTableSeatForSync :exec
INSERT INTO bridgeyok.table_seats (
    table_id,
    seat,
    participant_id,
    ready,
    controller_epoch,
    recovery_hash,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type InsertTableSeatForSyncParams struct {
	TableID         string             `json:"table_id"`
	Seat            string             `json:"seat"`
	ParticipantID   string             `json:"participant_id"`
	Ready           bool               `json:"ready"`
	ControllerEpoch int64              `json:"controller_epoch"`
	RecoveryHash    []byte             `json:"recovery_hash"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertTableSeatForSync(ctx context.Context, arg InsertTableSeatForSyncParams) error {
	_, err := q.db.Exec(ctx, insertTableSeatForSync,
		arg.TableID,
		arg.Seat,
		arg.ParticipantID,
		arg.Ready,
		arg.ControllerEpoch,
		arg.RecoveryHash,
		arg.UpdatedAt,
	)
	return err
}

const listGameEventsAfter = `-- name: ListGameEventsAfter :many
SELECT table_id,
       seq,
       revision,
       event_type,
       payload,
       occurred_at
FROM bridgeyok.game_events
WHERE table_id = $1
  AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListGameEventsAfterParams struct {
	TableID    string `json:"table_id"`
	AfterSeq   int64  `json:"after_seq"`
	EventLimit int32  `json:"event_limit"`
}

func (q *Queries) ListGameEventsAfter(ctx context.Context, arg ListGameEventsAfterParams) ([]BridgeyokGameEvent, error) {
	rows, err := q.db.Query(ctx, listGameEventsAfter, arg.TableID, arg.AfterSeq, arg.EventLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeyokGameEvent{}
	for rows.Next() {
		var i BridgeyokGameEvent
		if err := rows.Scan(
			&i.TableID,
			&i.Seq,
			&i.Revision,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatRecoveryHashes = `-- name: ListSeatRecoveryHashes :many
SELECT participant_id,
       recovery_hash
FROM bridgeyok.table_seats
WHERE table_id = $1
`

type ListSeatRecoveryHashesRow struct {
	ParticipantID string `json:"participant_id"`
	RecoveryHash  []byte `json:"recovery_hash"`
}

func (q *Queries) ListSeatRecoveryHashes(ctx context.Context, tableID string) ([]ListSeatRecoveryHashesRow, error) {
	rows, err := q.db.Query(ctx, listSeatRecoveryHashes, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeatRecoveryHashesRow{}
	for rows.Next() {
		var i ListSeatRecoveryHashesRow
		if err := rows.Scan(&i.ParticipantID, &i.RecoveryHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadGameSnapshot = `-- name: LoadGameSnapshot :one
SELECT board_id,
       schema_version,
       revision,
       last_seq,
       private_state
FROM bridgeyok.game_snapshots
WHERE table_id = $1
`

type LoadGameSnapshotRow struct {
	BoardID       pgtype.UUID `json:"board_id"`
	SchemaVersion int32       `json:"schema_version"`
	Revision      int64       `json:"revision"`
	LastSeq       int64       `json:"last_seq"`
	PrivateState  []byte      `json:"private_state"`
}

func (q *Queries) LoadGameSnapshot(ctx context.Context, tableID string) (LoadGameSnapshotRow, error) {
	row := q.db.QueryRow(ctx, loadGameSnapshot, tableID)
	var i LoadGameSnapshotRow
	err := row.Scan(
		&i.BoardID,
		&i.SchemaVersion,
		&i.Revision,
		&i.LastSeq,
		&i.PrivateState,
	)
	return i, err
}

const syncParticipantLeftAt = `-- name: SyncParticipantLeftAt :exec
UPDATE bridgeyok.table_participants
SET left_at = $1
WHERE table_id = $2
  AND id = $3
  AND left_at IS NULL
`

type SyncParticipantLeftAtParams struct {
	LeftAt        pgtype.Timestamptz `json:"left_at"`
	TableID       string             `json:"table_id"`
	ParticipantID string             `json:"participant_id"`
}

func (q *Queries) SyncParticipantLeftAt(ctx context.Context, arg SyncParticipantLeftAtParams) error {
	_, err := q.db.Exec(ctx, syncParticipantLeftAt, arg.LeftAt, arg.TableID, arg.ParticipantID)
	return err
}

const syncParticipantRole = `-- name: SyncParticipantRole :exec
UPDATE bridgeyok.table_participants
SET role = $1
WHERE table_id = $2
  AND id = $3
`

type SyncParticipantRoleParams struct {
	Role          string `json:"role"`
	TableID       string `json:"table_id"`
	ParticipantID string `json:"participant_id"`
}

func (q *Queries) SyncParticipantRole(ctx context.Context, arg SyncParticipantRoleParams) error {
	_, err := q.db.Exec(ctx, syncParticipantRole, arg.Role, arg.TableID, arg.ParticipantID)
	return err
}

const updateTableAfterCommand = `-- name: UpdateTableAfterCommand :execrows
UPDATE bridgeyok.tables
SET state = $1,
    locked = $2,
    owner_session_id = $3,
    revision = $4,
    next_seq = $5,
    meaningful_at = $6,
    finished_at = CASE WHEN $1 = 'FINISHED' THEN $6 ELSE finished_at END
WHERE id = $7
  AND revision = $8
`

type UpdateTableAfterCommandParams struct {
	State            string             `json:"state"`
	Locked           bool               `json:"locked"`
	OwnerSessionID   string             `json:"owner_session_id"`
	NextRevision     int64              `json:"next_revision"`
	NextSeq          int64              `json:"next_seq"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	ID               string             `json:"id"`
	ExpectedRevision int64              `json:"expected_revision"`
}

func (q *Queries) UpdateTableAfterCommand(ctx context.Context, arg UpdateTableAfterCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTableAfterCommand,
		arg.State,
		arg.Locked,
		arg.OwnerSessionID,
		arg.NextRevision,
		arg.NextSeq,
		arg.OccurredAt,
		arg.ID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertBoard = `-- name: UpsertBoard :exec
INSERT INTO bridgeyok.boards (
    id,
    table_id,
    board_number,
    dealer,
    vulnerability,
    ruleset_version,
    status,
    score_ns,
    result,
    created_at,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (table_id, id) DO UPDATE
SET status = EXCLUDED.status,
    score_ns = EXCLUDED.score_ns,
    result = EXCLUDED.result,
    completed_at = EXCLUDED.completed_at
`

type UpsertBoardParams struct {
	ID             string             `json:"id"`
	TableID        string             `json:"table_id"`
	BoardNumber    int32              `json:"board_number"`
	Dealer         string             `json:"dealer"`
	Vulnerability  string             `json:"vulnerability"`
	RulesetVersion string             `json:"ruleset_version"`
	Status         string             `json:"status"`
	ScoreNs        *int32             `json:"score_ns"`
	Result         []byte             `json:"result"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpsertBoard(ctx context.Context, arg UpsertBoardParams) error {
	_, err := q.db.Exec(ctx, upsertBoard,
		arg.ID,
		arg.TableID,
		arg.BoardNumber,
		arg.Dealer,
		arg.Vulnerability,
		arg.RulesetVersion,
		arg.Status,
		arg.ScoreNs,
		arg.Result,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}

const upsertGameSnapshot = `-- name: UpsertGameSnapshot :exec
INSERT INTO bridgeyok.game_snapshots (
    table_id,
    board_id,
    schema_version,
    revision,
    last_seq,
    private_state,
    updated_at
) VALUES (
    $1,
    $2,
    1,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (table_id) DO UPDATE
SET board_id = EXCLUDED.board_id,
    schema_version = EXCLUDED.schema_version,
    revision = EXCLUDED.revision,
    last_seq = EXCLUDED.last_seq,
    private_state = EXCLUDED.private_state,
    updated_at = EXCLUDED.updated_at
`

type UpsertGameSnapshotParams struct {
	TableID      string             `json:"table_id"`
	BoardID      pgtype.UUID        `json:"board_id"`
	Revision     int64              `json:"revision"`
	LastSeq      int64              `json:"last_seq"`
	PrivateState []byte             `json:"private_state"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertGameSnapshot(ctx context.Context, arg UpsertGameSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertGameSnapshot,
		arg.TableID,
		arg.BoardID,
		arg.Revision,
		arg.LastSeq,
		arg.PrivateState,
		arg.UpdatedAt,
	)
	return err
}
