// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRealtimeTicket = `-- name: ConsumeRealtimeTicket :one
WITH consumed AS (
    UPDATE bridgeyok.realtime_tickets
    SET used_at = $1
    WHERE ticket_hash = $2
      AND used_at IS NULL
      AND expires_at > $1
    RETURNING session_id
)
SELECT guest_sessions.id,
       guest_sessions.nickname,
       guest_sessions.status,
       guest_sessions.expires_at
FROM consumed
JOIN bridgeyok.guest_sessions
  ON guest_sessions.id = consumed.session_id
WHERE guest_sessions.status = 'ACTIVE'
  AND guest_sessions.expires_at > $1
`

type ConsumeRealtimeTicketParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	TicketHash []byte             `json:"ticket_hash"`
}

type ConsumeRealtimeTicketRow struct {
	ID        string             `json:"id"`
	Nickname  string             `json:"nickname"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ConsumeRealtimeTicket(ctx context.Context, arg ConsumeRealtimeTicketParams) (ConsumeRealtimeTicketRow, error) {
	row := q.db.QueryRow(ctx, consumeRealtimeTicket, arg.Now, arg.TicketHash)
	var i ConsumeRealtimeTicketRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const createGuestSession = `-- name: CreateGuestSession :exec
INSERT INTO bridgeyok.guest_sessions (
    id,
    credential_hash,
    nickname,
    status,
    created_at,
    last_seen_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    'ACTIVE',
    $4,
    $5,
    $6
)
`

type CreateGuestSessionParams struct {
	ID             string             `json:"id"`
	CredentialHash []byte             `json:"credential_hash"`
	Nickname       string             `json:"nickname"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGuestSession(ctx context.Context, arg CreateGuestSessionParams) error {
	_, err := q.db.Exec(ctx, createGuestSession,
		arg.ID,
		arg.CredentialHash,
		arg.Nickname,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const findActiveGuestSession = `-- name: FindActiveGuestSession :one
SELECT id, nickname, status, expires_at
FROM bridgeyok.guest_sessions
WHERE id = $1
  AND status = 'ACTIVE'
  AND expires_at > $2
`

type FindActiveGuestSessionParams struct {
	ID  string             `json:"id"`
	Now pgtype.Timestamptz `json:"now"`
}

type FindActiveGuestSessionRow struct {
	ID        string             `json:"id"`
	Nickname  string             `json:"nickname"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) FindActiveGuestSession(ctx context.Context, arg FindActiveGuestSessionParams) (FindActiveGuestSessionRow, error) {
	row := q.db.QueryRow(ctx, findActiveGuestSession, arg.ID, arg.Now)
	var i FindActiveGuestSessionRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeGuestSession = `-- name: RevokeGuestSession :execrows
UPDATE bridgeyok.guest_sessions
SET status = 'REVOKED',
    last_seen_at = $1
WHERE id = $2
  AND status = 'ACTIVE'
`

type RevokeGuestSessionParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  string             `json:"id"`
}

func (q *Queries) RevokeGuestSession(ctx context.Context, arg RevokeGuestSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGuestSession, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateGuestCredential = `-- name: RotateGuestCredential :one
UPDATE bridgeyok.guest_sessions
SET credential_hash = $1,
    last_seen_at = $2
WHERE credential_hash = $3
  AND status = 'ACTIVE'
  AND expires_at > $2
RETURNING id, nickname, status, expires_at
`

type RotateGuestCredentialParams struct {
	NewCredentialHash []byte             `json:"new_credential_hash"`
	Now               pgtype.Timestamptz `json:"now"`
	OldCredentialHash []byte             `json:"old_credential_hash"`
}

type RotateGuestCredentialRow struct {
	ID        string             `json:"id"`
	Nickname  string             `json:"nickname"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RotateGuestCredential(ctx context.Context, arg RotateGuestCredentialParams) (RotateGuestCredentialRow, error) {
	row := q.db.QueryRow(ctx, rotateGuestCredential, arg.NewCredentialHash, arg.Now, arg.OldCredentialHash)
	var i RotateGuestCredentialRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const storeRealtimeTicket = `-- name: StoreRealtimeTicket :exec
INSERT INTO bridgeyok.realtime_tickets (
    ticket_hash,
    session_id,
    created_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type StoreRealtimeTicketParams struct {
	TicketHash []byte             `json:"ticket_hash"`
	SessionID  string             `json:"session_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) StoreRealtimeTicket(ctx context.Context, arg StoreRealtimeTicketParams) error {
	_, err := q.db.Exec(ctx, storeRealtimeTicket,
		arg.TicketHash,
		arg.SessionID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
