// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingMatchInvitations = `-- name: CountPendingMatchInvitations :one
SELECT count(*) FROM bridgeyok.match_assignments a
JOIN bridgeyok.team_matches m ON m.id=a.match_id
WHERE a.session_id=$1 AND m.status IN ('WAITING','ACTIVE')
`

func (q *Queries) CountPendingMatchInvitations(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingMatchInvitations, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatch = `-- name: CreateMatch :exec
INSERT INTO bridgeyok.team_matches(id, owner_session_id, status, board_count, creation_hash, created_at, updated_at)
VALUES ($1, $2, 'WAITING', $3, $4, $5, $5)
`

type CreateMatchParams struct {
	ID             string             `json:"id"`
	OwnerSessionID string             `json:"owner_session_id"`
	BoardCount     int32              `json:"board_count"`
	CreationHash   []byte             `json:"creation_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) error {
	_, err := q.db.Exec(ctx, createMatch,
		arg.ID,
		arg.OwnerSessionID,
		arg.BoardCount,
		arg.CreationHash,
		arg.CreatedAt,
	)
	return err
}

const findMatchCreateRequest = `-- name: FindMatchCreateRequest :one
SELECT owner_session_id, request_id, request_hash, match_id FROM bridgeyok.match_create_requests WHERE owner_session_id=$1 AND request_id=$2
`

type FindMatchCreateRequestParams struct {
	OwnerSessionID string `json:"owner_session_id"`
	RequestID      string `json:"request_id"`
}

func (q *Queries) FindMatchCreateRequest(ctx context.Context, arg FindMatchCreateRequestParams) (BridgeyokMatchCreateRequest, error) {
	row := q.db.QueryRow(ctx, findMatchCreateRequest, arg.OwnerSessionID, arg.RequestID)
	var i BridgeyokMatchCreateRequest
	err := row.Scan(
		&i.OwnerSessionID,
		&i.RequestID,
		&i.RequestHash,
		&i.MatchID,
	)
	return i, err
}

const findMatchRoomBoard = `-- name: FindMatchRoomBoard :one
SELECT match_id, board_id, room, table_id, table_board_id FROM bridgeyok.match_room_boards WHERE table_board_id = $1
`

func (q *Queries) FindMatchRoomBoard(ctx context.Context, tableBoardID string) (BridgeyokMatchRoomBoard, error) {
	row := q.db.QueryRow(ctx, findMatchRoomBoard, tableBoardID)
	var i BridgeyokMatchRoomBoard
	err := row.Scan(
		&i.MatchID,
		&i.BoardID,
		&i.Room,
		&i.TableID,
		&i.TableBoardID,
	)
	return i, err
}

const findTableMatch = `-- name: FindTableMatch :one
SELECT match_id, room, table_id FROM bridgeyok.match_rooms WHERE table_id = $1
`

func (q *Queries) FindTableMatch(ctx context.Context, tableID string) (BridgeyokMatchRoom, error) {
	row := q.db.QueryRow(ctx, findTableMatch, tableID)
	var i BridgeyokMatchRoom
	err := row.Scan(&i.MatchID, &i.Room, &i.TableID)
	return i, err
}

const insertMatchAssignment = `-- name: InsertMatchAssignment :exec
INSERT INTO bridgeyok.match_assignments(match_id, room, seat, session_id, ready) VALUES ($1, $2, $3, $4, $5)
`

type InsertMatchAssignmentParams struct {
	MatchID   string `json:"match_id"`
	Room      string `json:"room"`
	Seat      string `json:"seat"`
	SessionID string `json:"session_id"`
	Ready     bool   `json:"ready"`
}

func (q *Queries) InsertMatchAssignment(ctx context.Context, arg InsertMatchAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertMatchAssignment,
		arg.MatchID,
		arg.Room,
		arg.Seat,
		arg.SessionID,
		arg.Ready,
	)
	return err
}

const insertMatchBoard = `-- name: InsertMatchBoard :exec
INSERT INTO bridgeyok.match_boards(match_id, id, board_number) VALUES ($1, $2, $3)
`

type InsertMatchBoardParams struct {
	MatchID     string `json:"match_id"`
	ID          string `json:"id"`
	BoardNumber int32  `json:"board_number"`
}

func (q *Queries) InsertMatchBoard(ctx context.Context, arg InsertMatchBoardParams) error {
	_, err := q.db.Exec(ctx, insertMatchBoard, arg.MatchID, arg.ID, arg.BoardNumber)
	return err
}

const insertMatchComparison = `-- name: InsertMatchComparison :execrows
INSERT INTO bridgeyok.match_comparisons(match_id, board_id, team_a_imp, compared_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (match_id, board_id) DO NOTHING
`

type InsertMatchComparisonParams struct {
	MatchID    string             `json:"match_id"`
	BoardID    string             `json:"board_id"`
	TeamAImp   int32              `json:"team_a_imp"`
	ComparedAt pgtype.Timestamptz `json:"compared_at"`
}

func (q *Queries) InsertMatchComparison(ctx context.Context, arg InsertMatchComparisonParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMatchComparison,
		arg.MatchID,
		arg.BoardID,
		arg.TeamAImp,
		arg.ComparedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMatchCreateRequest = `-- name: InsertMatchCreateRequest :exec
INSERT INTO bridgeyok.match_create_requests(owner_session_id,request_id,request_hash,match_id) VALUES ($1,$2,$3,$4)
`

type InsertMatchCreateRequestParams struct {
	OwnerSessionID string `json:"owner_session_id"`
	RequestID      string `json:"request_id"`
	RequestHash    []byte `json:"request_hash"`
	MatchID        string `json:"match_id"`
}

func (q *Queries) InsertMatchCreateRequest(ctx context.Context, arg InsertMatchCreateRequestParams) error {
	_, err := q.db.Exec(ctx, insertMatchCreateRequest,
		arg.OwnerSessionID,
		arg.RequestID,
		arg.RequestHash,
		arg.MatchID,
	)
	return err
}

const insertMatchResult = `-- name: InsertMatchResult :exec
INSERT INTO bridgeyok.match_results(match_id, board_id, room, table_board_id, score_ns, finalized_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMatchResultParams struct {
	MatchID      string             `json:"match_id"`
	BoardID      string             `json:"board_id"`
	Room         string             `json:"room"`
	TableBoardID string             `json:"table_board_id"`
	ScoreNs      int32              `json:"score_ns"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
}

func (q *Queries) InsertMatchResult(ctx context.Context, arg InsertMatchResultParams) error {
	_, err := q.db.Exec(ctx, insertMatchResult,
		arg.MatchID,
		arg.BoardID,
		arg.Room,
		arg.TableBoardID,
		arg.ScoreNs,
		arg.FinalizedAt,
	)
	return err
}

const insertMatchRoom = `-- name: InsertMatchRoom :exec
INSERT INTO bridgeyok.match_rooms(match_id, room, table_id) VALUES ($1, $2, $3)
`

type InsertMatchRoomParams struct {
	MatchID string `json:"match_id"`
	Room    string `json:"room"`
	TableID string `json:"table_id"`
}

func (q *Queries) InsertMatchRoom(ctx context.Context, arg InsertMatchRoomParams) error {
	_, err := q.db.Exec(ctx, insertMatchRoom, arg.MatchID, arg.Room, arg.TableID)
	return err
}

const insertMatchRoomBoard = `-- name: InsertMatchRoomBoard :exec
INSERT INTO bridgeyok.match_room_boards(match_id, board_id, room, table_id, table_board_id) VALUES ($1, $2, $3, $4, $5)
`

type InsertMatchRoomBoardParams struct {
	MatchID      string `json:"match_id"`
	BoardID      string `json:"board_id"`
	Room         string `json:"room"`
	TableID      string `json:"table_id"`
	TableBoardID string `json:"table_board_id"`
}

func (q *Queries) InsertMatchRoomBoard(ctx context.Context, arg InsertMatchRoomBoardParams) error {
	_, err := q.db.Exec(ctx, insertMatchRoomBoard,
		arg.MatchID,
		arg.BoardID,
		arg.Room,
		arg.TableID,
		arg.TableBoardID,
	)
	return err
}

const listMatchAssignments = `-- name: ListMatchAssignments :many
SELECT match_id, room, seat, session_id, ready FROM bridgeyok.match_assignments WHERE match_id = $1 ORDER BY room, seat
`

func (q *Queries) ListMatchAssignments(ctx context.Context, matchID string) ([]BridgeyokMatchAssignment, error) {
	rows, err := q.db.Query(ctx, listMatchAssignments, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeyokMatchAssignment{}
	for rows.Next() {
		var i BridgeyokMatchAssignment
		if err := rows.Scan(
			&i.MatchID,
			&i.Room,
			&i.Seat,
			&i.SessionID,
			&i.Ready,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchBoards = `-- name: ListMatchBoards :many
SELECT match_id, id, board_number, source_record FROM bridgeyok.match_boards WHERE match_id = $1 ORDER BY board_number
`

func (q *Queries) ListMatchBoards(ctx context.Context, matchID string) ([]BridgeyokMatchBoard, error) {
	rows, err := q.db.Query(ctx, listMatchBoards, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeyokMatchBoard{}
	for rows.Next() {
		var i BridgeyokMatchBoard
		if err := rows.Scan(
			&i.MatchID,
			&i.ID,
			&i.BoardNumber,
			&i.SourceRecord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchComparisons = `-- name: ListMatchComparisons :many
SELECT c.match_id, c.board_id, c.open_room, c.closed_room, c.team_a_imp, c.compared_at FROM bridgeyok.match_comparisons c
JOIN bridgeyok.match_boards b ON b.match_id = c.match_id AND b.id = c.board_id
WHERE c.match_id = $1 ORDER BY b.board_number
`

func (q *Queries) ListMatchComparisons(ctx context.Context, matchID string) ([]BridgeyokMatchComparison, error) {
	rows, err := q.db.Query(ctx, listMatchComparisons, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeyokMatchComparison{}
	for rows.Next() {
		var i BridgeyokMatchComparison
		if err := rows.Scan(
			&i.MatchID,
			&i.BoardID,
			&i.OpenRoom,
			&i.ClosedRoom,
			&i.TeamAImp,
			&i.ComparedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchResults = `-- name: ListMatchResults :many
SELECT r.match_id, r.board_id, r.room, r.table_board_id, r.score_ns, r.finalized_at FROM bridgeyok.match_results r
JOIN bridgeyok.match_boards b ON b.match_id = r.match_id AND b.id = r.board_id
WHERE r.match_id = $1 ORDER BY r.room, b.board_number
`

func (q *Queries) ListMatchResults(ctx context.Context, matchID string) ([]BridgeyokMatchResult, error) {
	rows, err := q.db.Query(ctx, listMatchResults, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeyokMatchResult{}
	for rows.Next() {
		var i BridgeyokMatchResult
		if err := rows.Scan(
			&i.MatchID,
			&i.BoardID,
			&i.Room,
			&i.TableBoardID,
			&i.ScoreNs,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchRooms = `-- name: ListMatchRooms :many
SELECT match_id, room, table_id FROM bridgeyok.match_rooms WHERE match_id = $1 ORDER BY room
`

func (q *Queries) ListMatchRooms(ctx context.Context, matchID string) ([]BridgeyokMatchRoom, error) {
	rows, err := q.db.Query(ctx, listMatchRooms, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeyokMatchRoom{}
	for rows.Next() {
		var i BridgeyokMatchRoom
		if err := rows.Scan(&i.MatchID, &i.Room, &i.TableID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantMatchIDs = `-- name: ListParticipantMatchIDs :many
SELECT m.id FROM bridgeyok.team_matches m
JOIN bridgeyok.match_assignments a ON a.match_id=m.id
WHERE a.session_id=$1
ORDER BY (m.status IN ('WAITING','ACTIVE')) DESC,m.updated_at DESC,m.id LIMIT 20
`

func (q *Queries) ListParticipantMatchIDs(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listParticipantMatchIDs, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadMatch = `-- name: LoadMatch :one
SELECT id, owner_session_id, status, board_count, revision, total_imp, creation_hash, created_at, updated_at FROM bridgeyok.team_matches WHERE id = $1
`

func (q *Queries) LoadMatch(ctx context.Context, id string) (BridgeyokTeamMatch, error) {
	row := q.db.QueryRow(ctx, loadMatch, id)
	var i BridgeyokTeamMatch
	err := row.Scan(
		&i.ID,
		&i.OwnerSessionID,
		&i.Status,
		&i.BoardCount,
		&i.Revision,
		&i.TotalImp,
		&i.CreationHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMatch = `-- name: LockMatch :one
SELECT id, owner_session_id, status, board_count, revision, total_imp, creation_hash, created_at, updated_at FROM bridgeyok.team_matches WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockMatch(ctx context.Context, id string) (BridgeyokTeamMatch, error) {
	row := q.db.QueryRow(ctx, lockMatch, id)
	var i BridgeyokTeamMatch
	err := row.Scan(
		&i.ID,
		&i.OwnerSessionID,
		&i.Status,
		&i.BoardCount,
		&i.Revision,
		&i.TotalImp,
		&i.CreationHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMatchPlayers = `-- name: LockMatchPlayers :many
SELECT id,session_id FROM bridgeyok.users WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

type LockMatchPlayersRow struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) LockMatchPlayers(ctx context.Context, userIds []string) ([]LockMatchPlayersRow, error) {
	rows, err := q.db.Query(ctx, lockMatchPlayers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockMatchPlayersRow{}
	for rows.Next() {
		var i LockMatchPlayersRow
		if err := rows.Scan(&i.ID, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMatchPlayer = `-- name: ResolveMatchPlayer :one
SELECT u.id, u.session_id, g.nickname FROM bridgeyok.users u
JOIN bridgeyok.guest_sessions g ON g.id=u.session_id
WHERE u.id=$1 AND g.status='ACTIVE' AND g.expires_at>$2
`

type ResolveMatchPlayerParams struct {
	ID        string             `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type ResolveMatchPlayerRow struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Nickname  string `json:"nickname"`
}

func (q *Queries) ResolveMatchPlayer(ctx context.Context, arg ResolveMatchPlayerParams) (ResolveMatchPlayerRow, error) {
	row := q.db.QueryRow(ctx, resolveMatchPlayer, arg.ID, arg.ExpiresAt)
	var i ResolveMatchPlayerRow
	err := row.Scan(&i.ID, &i.SessionID, &i.Nickname)
	return i, err
}

const setMatchBoardSource = `-- name: SetMatchBoardSource :execrows
UPDATE bridgeyok.match_boards SET source_record = $3 WHERE match_id = $1 AND id = $2 AND source_record IS NULL
`

type SetMatchBoardSourceParams struct {
	MatchID      string `json:"match_id"`
	ID           string `json:"id"`
	SourceRecord []byte `json:"source_record"`
}

func (q *Queries) SetMatchBoardSource(ctx context.Context, arg SetMatchBoardSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMatchBoardSource, arg.MatchID, arg.ID, arg.SourceRecord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMatchReady = `-- name: SetMatchReady :execrows
UPDATE bridgeyok.match_assignments SET ready = $3 WHERE match_id = $1 AND session_id = $2
`

type SetMatchReadyParams struct {
	MatchID   string `json:"match_id"`
	SessionID string `json:"session_id"`
	Ready     bool   `json:"ready"`
}

func (q *Queries) SetMatchReady(ctx context.Context, arg SetMatchReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMatchReady, arg.MatchID, arg.SessionID, arg.Ready)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMatch = `-- name: UpdateMatch :execrows
UPDATE bridgeyok.team_matches SET status = $2, total_imp = $3, revision = revision + 1, updated_at = $4
WHERE id = $1 AND revision = $5
`

type UpdateMatchParams struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	TotalImp  int32              `json:"total_imp"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Revision  int64              `json:"revision"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMatch,
		arg.ID,
		arg.Status,
		arg.TotalImp,
		arg.UpdatedAt,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
