// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readiness.sql

package dbgen

import (
	"context"
)

const isSchemaReady = `-- name: IsSchemaReady :one
SELECT (
    to_regclass('bridgeyok.tables') IS NOT NULL
    AND to_regclass('bridgeyok.match_create_requests') IS NOT NULL
    AND to_regclass('bridgeyok.team_matches') IS NOT NULL
    AND to_regclass('bridgeyok.match_results') IS NOT NULL
    AND to_regclass('bridgeyok.users') IS NOT NULL
    AND to_regclass('bridgeyok.chat_messages') IS NOT NULL
    AND to_regprocedure('bridgeyok.cleanup_chat_messages()') IS NOT NULL
)::boolean AS ready
`

func (q *Queries) IsSchemaReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isSchemaReady)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}
