// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readiness.sql

package dbgen

import (
	"context"
)

const isSchemaReady = `-- name: IsSchemaReady :one
SELECT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_namespace
    WHERE nspname = 'bridgeyok'
)::boolean AS ready
`

func (q *Queries) IsSchemaReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isSchemaReady)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}
