// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: table.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTable = `-- name: CreateTable :exec
INSERT INTO bridgeyok.tables (
    id,
    owner_session_id,
    invite_code_hash,
    state,
    locked,
    revision,
    next_seq,
    created_at,
    meaningful_at
) VALUES (
    $1,
    $2,
    $3,
    'WAITING',
    false,
    0,
    1,
    $4,
    $4
)
`

type CreateTableParams struct {
	ID             string             `json:"id"`
	OwnerSessionID string             `json:"owner_session_id"`
	InviteCodeHash []byte             `json:"invite_code_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) error {
	_, err := q.db.Exec(ctx, createTable,
		arg.ID,
		arg.OwnerSessionID,
		arg.InviteCodeHash,
		arg.CreatedAt,
	)
	return err
}

const createTableParticipant = `-- name: CreateTableParticipant :exec
INSERT INTO bridgeyok.table_participants (
    id,
    table_id,
    session_id,
    role,
    joined_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateTableParticipantParams struct {
	ID        string             `json:"id"`
	TableID   string             `json:"table_id"`
	SessionID string             `json:"session_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateTableParticipant(ctx context.Context, arg CreateTableParticipantParams) error {
	_, err := q.db.Exec(ctx, createTableParticipant,
		arg.ID,
		arg.TableID,
		arg.SessionID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const findTableByID = `-- name: FindTableByID :one
SELECT id,
       owner_session_id,
       state,
       locked,
       revision,
       (next_seq - 1)::bigint AS last_seq
FROM bridgeyok.tables
WHERE id = $1
`

type FindTableByIDRow struct {
	ID             string `json:"id"`
	OwnerSessionID string `json:"owner_session_id"`
	State          string `json:"state"`
	Locked         bool   `json:"locked"`
	Revision       int64  `json:"revision"`
	LastSeq        int64  `json:"last_seq"`
}

func (q *Queries) FindTableByID(ctx context.Context, id string) (FindTableByIDRow, error) {
	row := q.db.QueryRow(ctx, findTableByID, id)
	var i FindTableByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSessionID,
		&i.State,
		&i.Locked,
		&i.Revision,
		&i.LastSeq,
	)
	return i, err
}

const listActiveTableParticipants = `-- name: ListActiveTableParticipants :many
SELECT table_participants.id,
       table_participants.session_id,
       table_participants.role,
       table_participants.joined_at,
       table_participants.left_at,
       guest_sessions.nickname
FROM bridgeyok.table_participants
JOIN bridgeyok.guest_sessions
  ON guest_sessions.id = table_participants.session_id
WHERE table_participants.table_id = $1
  AND table_participants.left_at IS NULL
ORDER BY joined_at, table_participants.id
`

type ListActiveTableParticipantsRow struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	LeftAt    pgtype.Timestamptz `json:"left_at"`
	Nickname  string             `json:"nickname"`
}

func (q *Queries) ListActiveTableParticipants(ctx context.Context, tableID string) ([]ListActiveTableParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTableParticipants, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTableParticipantsRow{}
	for rows.Next() {
		var i ListActiveTableParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInactiveTables = `-- name: ListInactiveTables :many
SELECT id,
       owner_session_id,
       revision
FROM bridgeyok.tables
WHERE state IN ('WAITING', 'ACTIVE', 'BETWEEN_BOARDS', 'PAUSED')
  AND meaningful_at <= $1
ORDER BY meaningful_at, id
LIMIT $2
`

type ListInactiveTablesParams struct {
	InactiveBefore pgtype.Timestamptz `json:"inactive_before"`
	TableLimit     int32              `json:"table_limit"`
}

type ListInactiveTablesRow struct {
	ID             string `json:"id"`
	OwnerSessionID string `json:"owner_session_id"`
	Revision       int64  `json:"revision"`
}

func (q *Queries) ListInactiveTables(ctx context.Context, arg ListInactiveTablesParams) ([]ListInactiveTablesRow, error) {
	rows, err := q.db.Query(ctx, listInactiveTables, arg.InactiveBefore, arg.TableLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInactiveTablesRow{}
	for rows.Next() {
		var i ListInactiveTablesRow
		if err := rows.Scan(&i.ID, &i.OwnerSessionID, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableSeats = `-- name: ListTableSeats :many
SELECT seat,
       participant_id,
       ready,
       controller_epoch
FROM bridgeyok.table_seats
WHERE table_id = $1
ORDER BY seat
`

type ListTableSeatsRow struct {
	Seat            string `json:"seat"`
	ParticipantID   string `json:"participant_id"`
	Ready           bool   `json:"ready"`
	ControllerEpoch int64  `json:"controller_epoch"`
}

func (q *Queries) ListTableSeats(ctx context.Context, tableID string) ([]ListTableSeatsRow, error) {
	rows, err := q.db.Query(ctx, listTableSeats, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTableSeatsRow{}
	for rows.Next() {
		var i ListTableSeatsRow
		if err := rows.Scan(
			&i.Seat,
			&i.ParticipantID,
			&i.Ready,
			&i.ControllerEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTableByID = `-- name: LockTableByID :one
SELECT id,
       owner_session_id,
       state,
       locked,
       revision,
       (next_seq - 1)::bigint AS last_seq
FROM bridgeyok.tables
WHERE id = $1
FOR UPDATE
`

type LockTableByIDRow struct {
	ID             string `json:"id"`
	OwnerSessionID string `json:"owner_session_id"`
	State          string `json:"state"`
	Locked         bool   `json:"locked"`
	Revision       int64  `json:"revision"`
	LastSeq        int64  `json:"last_seq"`
}

func (q *Queries) LockTableByID(ctx context.Context, id string) (LockTableByIDRow, error) {
	row := q.db.QueryRow(ctx, lockTableByID, id)
	var i LockTableByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSessionID,
		&i.State,
		&i.Locked,
		&i.Revision,
		&i.LastSeq,
	)
	return i, err
}

const lockTableByInvite = `-- name: LockTableByInvite :one
SELECT id,
       owner_session_id,
       state,
       locked,
       revision,
       (next_seq - 1)::bigint AS last_seq
FROM bridgeyok.tables
WHERE invite_code_hash = $1
FOR UPDATE
`

type LockTableByInviteRow struct {
	ID             string `json:"id"`
	OwnerSessionID string `json:"owner_session_id"`
	State          string `json:"state"`
	Locked         bool   `json:"locked"`
	Revision       int64  `json:"revision"`
	LastSeq        int64  `json:"last_seq"`
}

func (q *Queries) LockTableByInvite(ctx context.Context, inviteCodeHash []byte) (LockTableByInviteRow, error) {
	row := q.db.QueryRow(ctx, lockTableByInvite, inviteCodeHash)
	var i LockTableByInviteRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSessionID,
		&i.State,
		&i.Locked,
		&i.Revision,
		&i.LastSeq,
	)
	return i, err
}

const previewTable = `-- name: PreviewTable :one
SELECT tables.state,
       tables.locked,
       count(table_participants.id) FILTER (WHERE table_participants.left_at IS NULL)::integer AS participant_count
FROM bridgeyok.tables AS tables
LEFT JOIN bridgeyok.table_participants AS table_participants
  ON table_participants.table_id = tables.id
WHERE tables.invite_code_hash = $1
GROUP BY tables.id
`

type PreviewTableRow struct {
	State            string `json:"state"`
	Locked           bool   `json:"locked"`
	ParticipantCount int32  `json:"participant_count"`
}

func (q *Queries) PreviewTable(ctx context.Context, inviteCodeHash []byte) (PreviewTableRow, error) {
	row := q.db.QueryRow(ctx, previewTable, inviteCodeHash)
	var i PreviewTableRow
	err := row.Scan(&i.State, &i.Locked, &i.ParticipantCount)
	return i, err
}
